// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: evm.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Token, tokenFromJSON, tokenToJSON } from "./base";

export const protobufPackage = "evm";

export interface GetChainByNameRequest {
  name: string;
}

export interface GetChainByIdRequest {
  id: number;
}

export interface ChainDetails {
  id: number;
  name: string;
  shortName: string;
  ogName: string;
}

export interface GetTokenDetailsRequest {
  token: Token;
  chainId?: number | undefined;
  chainName?: string | undefined;
}

export interface TokenDetails {
  symbol: string;
  address: string;
  decimals: number;
  chain?: ChainDetails | undefined;
}

export interface GetAllChainsRequest {
}

export interface AllChains {
  chains: ChainDetails[];
}

export interface GetAllTokensRequest {
}

export interface AllTokens {
  tokens: TokenDetails[];
}

function createBaseGetChainByNameRequest(): GetChainByNameRequest {
  return { name: "" };
}

export const GetChainByNameRequest: MessageFns<GetChainByNameRequest> = {
  encode(message: GetChainByNameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetChainByNameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetChainByNameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetChainByNameRequest {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: GetChainByNameRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetChainByNameRequest>, I>>(base?: I): GetChainByNameRequest {
    return GetChainByNameRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetChainByNameRequest>, I>>(object: I): GetChainByNameRequest {
    const message = createBaseGetChainByNameRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseGetChainByIdRequest(): GetChainByIdRequest {
  return { id: 0 };
}

export const GetChainByIdRequest: MessageFns<GetChainByIdRequest> = {
  encode(message: GetChainByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetChainByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetChainByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetChainByIdRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: GetChainByIdRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetChainByIdRequest>, I>>(base?: I): GetChainByIdRequest {
    return GetChainByIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetChainByIdRequest>, I>>(object: I): GetChainByIdRequest {
    const message = createBaseGetChainByIdRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseChainDetails(): ChainDetails {
  return { id: 0, name: "", shortName: "", ogName: "" };
}

export const ChainDetails: MessageFns<ChainDetails> = {
  encode(message: ChainDetails, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.shortName !== "") {
      writer.uint32(26).string(message.shortName);
    }
    if (message.ogName !== "") {
      writer.uint32(34).string(message.ogName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChainDetails {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChainDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.shortName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ogName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChainDetails {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      shortName: isSet(object.shortName)
        ? globalThis.String(object.shortName)
        : isSet(object.short_name)
        ? globalThis.String(object.short_name)
        : "",
      ogName: isSet(object.ogName)
        ? globalThis.String(object.ogName)
        : isSet(object.og_name)
        ? globalThis.String(object.og_name)
        : "",
    };
  },

  toJSON(message: ChainDetails): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.shortName !== "") {
      obj.shortName = message.shortName;
    }
    if (message.ogName !== "") {
      obj.ogName = message.ogName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChainDetails>, I>>(base?: I): ChainDetails {
    return ChainDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChainDetails>, I>>(object: I): ChainDetails {
    const message = createBaseChainDetails();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.shortName = object.shortName ?? "";
    message.ogName = object.ogName ?? "";
    return message;
  },
};

function createBaseGetTokenDetailsRequest(): GetTokenDetailsRequest {
  return { token: 0, chainId: undefined, chainName: undefined };
}

export const GetTokenDetailsRequest: MessageFns<GetTokenDetailsRequest> = {
  encode(message: GetTokenDetailsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== 0) {
      writer.uint32(8).int32(message.token);
    }
    if (message.chainId !== undefined) {
      writer.uint32(16).int32(message.chainId);
    }
    if (message.chainName !== undefined) {
      writer.uint32(26).string(message.chainName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTokenDetailsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTokenDetailsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.chainId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.chainName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTokenDetailsRequest {
    return {
      token: isSet(object.token) ? tokenFromJSON(object.token) : 0,
      chainId: isSet(object.chainId)
        ? globalThis.Number(object.chainId)
        : isSet(object.chain_id)
        ? globalThis.Number(object.chain_id)
        : undefined,
      chainName: isSet(object.chainName)
        ? globalThis.String(object.chainName)
        : isSet(object.chain_name)
        ? globalThis.String(object.chain_name)
        : undefined,
    };
  },

  toJSON(message: GetTokenDetailsRequest): unknown {
    const obj: any = {};
    if (message.token !== 0) {
      obj.token = tokenToJSON(message.token);
    }
    if (message.chainId !== undefined) {
      obj.chainId = Math.round(message.chainId);
    }
    if (message.chainName !== undefined) {
      obj.chainName = message.chainName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTokenDetailsRequest>, I>>(base?: I): GetTokenDetailsRequest {
    return GetTokenDetailsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTokenDetailsRequest>, I>>(object: I): GetTokenDetailsRequest {
    const message = createBaseGetTokenDetailsRequest();
    message.token = object.token ?? 0;
    message.chainId = object.chainId ?? undefined;
    message.chainName = object.chainName ?? undefined;
    return message;
  },
};

function createBaseTokenDetails(): TokenDetails {
  return { symbol: "", address: "", decimals: 0, chain: undefined };
}

export const TokenDetails: MessageFns<TokenDetails> = {
  encode(message: TokenDetails, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.address !== "") {
      writer.uint32(18).string(message.address);
    }
    if (message.decimals !== 0) {
      writer.uint32(24).int32(message.decimals);
    }
    if (message.chain !== undefined) {
      ChainDetails.encode(message.chain, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TokenDetails {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTokenDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.decimals = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.chain = ChainDetails.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TokenDetails {
    return {
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      decimals: isSet(object.decimals) ? globalThis.Number(object.decimals) : 0,
      chain: isSet(object.chain) ? ChainDetails.fromJSON(object.chain) : undefined,
    };
  },

  toJSON(message: TokenDetails): unknown {
    const obj: any = {};
    if (message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.decimals !== 0) {
      obj.decimals = Math.round(message.decimals);
    }
    if (message.chain !== undefined) {
      obj.chain = ChainDetails.toJSON(message.chain);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TokenDetails>, I>>(base?: I): TokenDetails {
    return TokenDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TokenDetails>, I>>(object: I): TokenDetails {
    const message = createBaseTokenDetails();
    message.symbol = object.symbol ?? "";
    message.address = object.address ?? "";
    message.decimals = object.decimals ?? 0;
    message.chain = (object.chain !== undefined && object.chain !== null)
      ? ChainDetails.fromPartial(object.chain)
      : undefined;
    return message;
  },
};

function createBaseGetAllChainsRequest(): GetAllChainsRequest {
  return {};
}

export const GetAllChainsRequest: MessageFns<GetAllChainsRequest> = {
  encode(_: GetAllChainsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllChainsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllChainsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetAllChainsRequest {
    return {};
  },

  toJSON(_: GetAllChainsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAllChainsRequest>, I>>(base?: I): GetAllChainsRequest {
    return GetAllChainsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAllChainsRequest>, I>>(_: I): GetAllChainsRequest {
    const message = createBaseGetAllChainsRequest();
    return message;
  },
};

function createBaseAllChains(): AllChains {
  return { chains: [] };
}

export const AllChains: MessageFns<AllChains> = {
  encode(message: AllChains, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.chains) {
      ChainDetails.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AllChains {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAllChains();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chains.push(ChainDetails.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AllChains {
    return {
      chains: globalThis.Array.isArray(object?.chains) ? object.chains.map((e: any) => ChainDetails.fromJSON(e)) : [],
    };
  },

  toJSON(message: AllChains): unknown {
    const obj: any = {};
    if (message.chains?.length) {
      obj.chains = message.chains.map((e) => ChainDetails.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AllChains>, I>>(base?: I): AllChains {
    return AllChains.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AllChains>, I>>(object: I): AllChains {
    const message = createBaseAllChains();
    message.chains = object.chains?.map((e) => ChainDetails.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetAllTokensRequest(): GetAllTokensRequest {
  return {};
}

export const GetAllTokensRequest: MessageFns<GetAllTokensRequest> = {
  encode(_: GetAllTokensRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllTokensRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllTokensRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetAllTokensRequest {
    return {};
  },

  toJSON(_: GetAllTokensRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAllTokensRequest>, I>>(base?: I): GetAllTokensRequest {
    return GetAllTokensRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAllTokensRequest>, I>>(_: I): GetAllTokensRequest {
    const message = createBaseGetAllTokensRequest();
    return message;
  },
};

function createBaseAllTokens(): AllTokens {
  return { tokens: [] };
}

export const AllTokens: MessageFns<AllTokens> = {
  encode(message: AllTokens, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tokens) {
      TokenDetails.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AllTokens {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAllTokens();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tokens.push(TokenDetails.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AllTokens {
    return {
      tokens: globalThis.Array.isArray(object?.tokens) ? object.tokens.map((e: any) => TokenDetails.fromJSON(e)) : [],
    };
  },

  toJSON(message: AllTokens): unknown {
    const obj: any = {};
    if (message.tokens?.length) {
      obj.tokens = message.tokens.map((e) => TokenDetails.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AllTokens>, I>>(base?: I): AllTokens {
    return AllTokens.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AllTokens>, I>>(object: I): AllTokens {
    const message = createBaseAllTokens();
    message.tokens = object.tokens?.map((e) => TokenDetails.fromPartial(e)) || [];
    return message;
  },
};

export type EvmDefinition = typeof EvmDefinition;
export const EvmDefinition = {
  name: "Evm",
  fullName: "evm.Evm",
  methods: {
    getChainByName: {
      name: "GetChainByName",
      requestType: GetChainByNameRequest as typeof GetChainByNameRequest,
      requestStream: false,
      responseType: ChainDetails as typeof ChainDetails,
      responseStream: false,
      options: {},
    },
    getChainById: {
      name: "GetChainById",
      requestType: GetChainByIdRequest as typeof GetChainByIdRequest,
      requestStream: false,
      responseType: ChainDetails as typeof ChainDetails,
      responseStream: false,
      options: {},
    },
    getTokenDetails: {
      name: "GetTokenDetails",
      requestType: GetTokenDetailsRequest as typeof GetTokenDetailsRequest,
      requestStream: false,
      responseType: TokenDetails as typeof TokenDetails,
      responseStream: false,
      options: {},
    },
    getAllChains: {
      name: "GetAllChains",
      requestType: GetAllChainsRequest as typeof GetAllChainsRequest,
      requestStream: false,
      responseType: AllChains as typeof AllChains,
      responseStream: false,
      options: {},
    },
    getAllTokens: {
      name: "GetAllTokens",
      requestType: GetAllTokensRequest as typeof GetAllTokensRequest,
      requestStream: false,
      responseType: AllTokens as typeof AllTokens,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface EvmServiceImplementation<CallContextExt = {}> {
  getChainByName(
    request: GetChainByNameRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ChainDetails>>;
  getChainById(request: GetChainByIdRequest, context: CallContext & CallContextExt): Promise<DeepPartial<ChainDetails>>;
  getTokenDetails(
    request: GetTokenDetailsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<TokenDetails>>;
  getAllChains(request: GetAllChainsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<AllChains>>;
  getAllTokens(request: GetAllTokensRequest, context: CallContext & CallContextExt): Promise<DeepPartial<AllTokens>>;
}

export interface EvmClient<CallOptionsExt = {}> {
  getChainByName(
    request: DeepPartial<GetChainByNameRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ChainDetails>;
  getChainById(
    request: DeepPartial<GetChainByIdRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ChainDetails>;
  getTokenDetails(
    request: DeepPartial<GetTokenDetailsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<TokenDetails>;
  getAllChains(request: DeepPartial<GetAllChainsRequest>, options?: CallOptions & CallOptionsExt): Promise<AllChains>;
  getAllTokens(request: DeepPartial<GetAllTokensRequest>, options?: CallOptions & CallOptionsExt): Promise<AllTokens>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
