// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: kamino.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Token, tokenFromJSON, tokenToJSON } from "./base";
import { Struct } from "./google/protobuf/struct";

export const protobufPackage = "kamino";

export interface BorrowCapacityRequest {
}

export interface BorrowCapacityResponse {
  borrowCapacity: number;
}

export interface GetStatsRequest {
}

export interface RefreshStatsRequest {
}

export interface StatsResponse {
  collateralDeposited: number;
  borrowLimit: number;
  collateralUtilization: number;
  borrowCapacity: number;
  totalBorrowed: number;
  ltv: number;
  depositTvl: number;
  borrowTvl: number;
  accumulatedProtocolFees: number;
  liquidityAvailable: number;
  misc?: { [key: string]: any } | undefined;
}

export interface CbrRequest {
  token?: Token | undefined;
}

export interface CbrResponse {
  cumulativeBorrowRate: number;
}

export interface EstimateYieldRequest {
  amount: string;
  prevCumulativeBorrowRate: string;
  token?: Token | undefined;
}

export interface EstimateYieldResponse {
  yieldEstimate: number;
}

export interface DepositRequest {
  amount: string;
  token?: Token | undefined;
}

export interface BorrowRequest {
  requestId: string;
  amount: string;
  token?: Token | undefined;
}

export interface RepayRequest {
  requestId: string;
  amount: string;
  token?: Token | undefined;
}

export interface WithdrawRequest {
  amount: string;
  token?: Token | undefined;
}

export interface DepositCollateralRequest {
  amount: string;
}

export interface KaminoTx {
  amount: string;
  asset: string;
  txType: string;
  signature: string;
  txCost: number;
  timeStamp: number;
  requestId?: string | undefined;
}

function createBaseBorrowCapacityRequest(): BorrowCapacityRequest {
  return {};
}

export const BorrowCapacityRequest: MessageFns<BorrowCapacityRequest> = {
  encode(_: BorrowCapacityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BorrowCapacityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBorrowCapacityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): BorrowCapacityRequest {
    return {};
  },

  toJSON(_: BorrowCapacityRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<BorrowCapacityRequest>, I>>(base?: I): BorrowCapacityRequest {
    return BorrowCapacityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BorrowCapacityRequest>, I>>(_: I): BorrowCapacityRequest {
    const message = createBaseBorrowCapacityRequest();
    return message;
  },
};

function createBaseBorrowCapacityResponse(): BorrowCapacityResponse {
  return { borrowCapacity: 0 };
}

export const BorrowCapacityResponse: MessageFns<BorrowCapacityResponse> = {
  encode(message: BorrowCapacityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.borrowCapacity !== 0) {
      writer.uint32(9).double(message.borrowCapacity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BorrowCapacityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBorrowCapacityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.borrowCapacity = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BorrowCapacityResponse {
    return {
      borrowCapacity: isSet(object.borrowCapacity)
        ? globalThis.Number(object.borrowCapacity)
        : isSet(object.borrow_capacity)
        ? globalThis.Number(object.borrow_capacity)
        : 0,
    };
  },

  toJSON(message: BorrowCapacityResponse): unknown {
    const obj: any = {};
    if (message.borrowCapacity !== 0) {
      obj.borrowCapacity = message.borrowCapacity;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BorrowCapacityResponse>, I>>(base?: I): BorrowCapacityResponse {
    return BorrowCapacityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BorrowCapacityResponse>, I>>(object: I): BorrowCapacityResponse {
    const message = createBaseBorrowCapacityResponse();
    message.borrowCapacity = object.borrowCapacity ?? 0;
    return message;
  },
};

function createBaseGetStatsRequest(): GetStatsRequest {
  return {};
}

export const GetStatsRequest: MessageFns<GetStatsRequest> = {
  encode(_: GetStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetStatsRequest {
    return {};
  },

  toJSON(_: GetStatsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStatsRequest>, I>>(base?: I): GetStatsRequest {
    return GetStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStatsRequest>, I>>(_: I): GetStatsRequest {
    const message = createBaseGetStatsRequest();
    return message;
  },
};

function createBaseRefreshStatsRequest(): RefreshStatsRequest {
  return {};
}

export const RefreshStatsRequest: MessageFns<RefreshStatsRequest> = {
  encode(_: RefreshStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RefreshStatsRequest {
    return {};
  },

  toJSON(_: RefreshStatsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshStatsRequest>, I>>(base?: I): RefreshStatsRequest {
    return RefreshStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshStatsRequest>, I>>(_: I): RefreshStatsRequest {
    const message = createBaseRefreshStatsRequest();
    return message;
  },
};

function createBaseStatsResponse(): StatsResponse {
  return {
    collateralDeposited: 0,
    borrowLimit: 0,
    collateralUtilization: 0,
    borrowCapacity: 0,
    totalBorrowed: 0,
    ltv: 0,
    depositTvl: 0,
    borrowTvl: 0,
    accumulatedProtocolFees: 0,
    liquidityAvailable: 0,
    misc: undefined,
  };
}

export const StatsResponse: MessageFns<StatsResponse> = {
  encode(message: StatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.collateralDeposited !== 0) {
      writer.uint32(9).double(message.collateralDeposited);
    }
    if (message.borrowLimit !== 0) {
      writer.uint32(17).double(message.borrowLimit);
    }
    if (message.collateralUtilization !== 0) {
      writer.uint32(25).double(message.collateralUtilization);
    }
    if (message.borrowCapacity !== 0) {
      writer.uint32(33).double(message.borrowCapacity);
    }
    if (message.totalBorrowed !== 0) {
      writer.uint32(41).double(message.totalBorrowed);
    }
    if (message.ltv !== 0) {
      writer.uint32(49).double(message.ltv);
    }
    if (message.depositTvl !== 0) {
      writer.uint32(57).double(message.depositTvl);
    }
    if (message.borrowTvl !== 0) {
      writer.uint32(65).double(message.borrowTvl);
    }
    if (message.accumulatedProtocolFees !== 0) {
      writer.uint32(73).double(message.accumulatedProtocolFees);
    }
    if (message.liquidityAvailable !== 0) {
      writer.uint32(81).double(message.liquidityAvailable);
    }
    if (message.misc !== undefined) {
      Struct.encode(Struct.wrap(message.misc), writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.collateralDeposited = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.borrowLimit = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.collateralUtilization = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.borrowCapacity = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.totalBorrowed = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.ltv = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 57) {
            break;
          }

          message.depositTvl = reader.double();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.borrowTvl = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.accumulatedProtocolFees = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 81) {
            break;
          }

          message.liquidityAvailable = reader.double();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.misc = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StatsResponse {
    return {
      collateralDeposited: isSet(object.collateralDeposited)
        ? globalThis.Number(object.collateralDeposited)
        : isSet(object.collateral_deposited)
        ? globalThis.Number(object.collateral_deposited)
        : 0,
      borrowLimit: isSet(object.borrowLimit)
        ? globalThis.Number(object.borrowLimit)
        : isSet(object.borrow_limit)
        ? globalThis.Number(object.borrow_limit)
        : 0,
      collateralUtilization: isSet(object.collateralUtilization)
        ? globalThis.Number(object.collateralUtilization)
        : isSet(object.collateral_utilization)
        ? globalThis.Number(object.collateral_utilization)
        : 0,
      borrowCapacity: isSet(object.borrowCapacity)
        ? globalThis.Number(object.borrowCapacity)
        : isSet(object.borrow_capacity)
        ? globalThis.Number(object.borrow_capacity)
        : 0,
      totalBorrowed: isSet(object.totalBorrowed)
        ? globalThis.Number(object.totalBorrowed)
        : isSet(object.total_borrowed)
        ? globalThis.Number(object.total_borrowed)
        : 0,
      ltv: isSet(object.ltv) ? globalThis.Number(object.ltv) : 0,
      depositTvl: isSet(object.depositTvl)
        ? globalThis.Number(object.depositTvl)
        : isSet(object.deposit_tvl)
        ? globalThis.Number(object.deposit_tvl)
        : 0,
      borrowTvl: isSet(object.borrowTvl)
        ? globalThis.Number(object.borrowTvl)
        : isSet(object.borrow_tvl)
        ? globalThis.Number(object.borrow_tvl)
        : 0,
      accumulatedProtocolFees: isSet(object.accumulatedProtocolFees)
        ? globalThis.Number(object.accumulatedProtocolFees)
        : isSet(object.accumulated_protocol_fees)
        ? globalThis.Number(object.accumulated_protocol_fees)
        : 0,
      liquidityAvailable: isSet(object.liquidityAvailable)
        ? globalThis.Number(object.liquidityAvailable)
        : isSet(object.liquidity_available)
        ? globalThis.Number(object.liquidity_available)
        : 0,
      misc: isObject(object.misc) ? object.misc : undefined,
    };
  },

  toJSON(message: StatsResponse): unknown {
    const obj: any = {};
    if (message.collateralDeposited !== 0) {
      obj.collateralDeposited = message.collateralDeposited;
    }
    if (message.borrowLimit !== 0) {
      obj.borrowLimit = message.borrowLimit;
    }
    if (message.collateralUtilization !== 0) {
      obj.collateralUtilization = message.collateralUtilization;
    }
    if (message.borrowCapacity !== 0) {
      obj.borrowCapacity = message.borrowCapacity;
    }
    if (message.totalBorrowed !== 0) {
      obj.totalBorrowed = message.totalBorrowed;
    }
    if (message.ltv !== 0) {
      obj.ltv = message.ltv;
    }
    if (message.depositTvl !== 0) {
      obj.depositTvl = message.depositTvl;
    }
    if (message.borrowTvl !== 0) {
      obj.borrowTvl = message.borrowTvl;
    }
    if (message.accumulatedProtocolFees !== 0) {
      obj.accumulatedProtocolFees = message.accumulatedProtocolFees;
    }
    if (message.liquidityAvailable !== 0) {
      obj.liquidityAvailable = message.liquidityAvailable;
    }
    if (message.misc !== undefined) {
      obj.misc = message.misc;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StatsResponse>, I>>(base?: I): StatsResponse {
    return StatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StatsResponse>, I>>(object: I): StatsResponse {
    const message = createBaseStatsResponse();
    message.collateralDeposited = object.collateralDeposited ?? 0;
    message.borrowLimit = object.borrowLimit ?? 0;
    message.collateralUtilization = object.collateralUtilization ?? 0;
    message.borrowCapacity = object.borrowCapacity ?? 0;
    message.totalBorrowed = object.totalBorrowed ?? 0;
    message.ltv = object.ltv ?? 0;
    message.depositTvl = object.depositTvl ?? 0;
    message.borrowTvl = object.borrowTvl ?? 0;
    message.accumulatedProtocolFees = object.accumulatedProtocolFees ?? 0;
    message.liquidityAvailable = object.liquidityAvailable ?? 0;
    message.misc = object.misc ?? undefined;
    return message;
  },
};

function createBaseCbrRequest(): CbrRequest {
  return { token: undefined };
}

export const CbrRequest: MessageFns<CbrRequest> = {
  encode(message: CbrRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== undefined) {
      writer.uint32(8).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CbrRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCbrRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CbrRequest {
    return { token: isSet(object.token) ? tokenFromJSON(object.token) : undefined };
  },

  toJSON(message: CbrRequest): unknown {
    const obj: any = {};
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CbrRequest>, I>>(base?: I): CbrRequest {
    return CbrRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CbrRequest>, I>>(object: I): CbrRequest {
    const message = createBaseCbrRequest();
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseCbrResponse(): CbrResponse {
  return { cumulativeBorrowRate: 0 };
}

export const CbrResponse: MessageFns<CbrResponse> = {
  encode(message: CbrResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cumulativeBorrowRate !== 0) {
      writer.uint32(9).double(message.cumulativeBorrowRate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CbrResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCbrResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.cumulativeBorrowRate = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CbrResponse {
    return {
      cumulativeBorrowRate: isSet(object.cumulativeBorrowRate)
        ? globalThis.Number(object.cumulativeBorrowRate)
        : isSet(object.cumulative_borrow_rate)
        ? globalThis.Number(object.cumulative_borrow_rate)
        : 0,
    };
  },

  toJSON(message: CbrResponse): unknown {
    const obj: any = {};
    if (message.cumulativeBorrowRate !== 0) {
      obj.cumulativeBorrowRate = message.cumulativeBorrowRate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CbrResponse>, I>>(base?: I): CbrResponse {
    return CbrResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CbrResponse>, I>>(object: I): CbrResponse {
    const message = createBaseCbrResponse();
    message.cumulativeBorrowRate = object.cumulativeBorrowRate ?? 0;
    return message;
  },
};

function createBaseEstimateYieldRequest(): EstimateYieldRequest {
  return { amount: "", prevCumulativeBorrowRate: "", token: undefined };
}

export const EstimateYieldRequest: MessageFns<EstimateYieldRequest> = {
  encode(message: EstimateYieldRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== "") {
      writer.uint32(10).string(message.amount);
    }
    if (message.prevCumulativeBorrowRate !== "") {
      writer.uint32(18).string(message.prevCumulativeBorrowRate);
    }
    if (message.token !== undefined) {
      writer.uint32(24).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EstimateYieldRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEstimateYieldRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.prevCumulativeBorrowRate = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EstimateYieldRequest {
    return {
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      prevCumulativeBorrowRate: isSet(object.prevCumulativeBorrowRate)
        ? globalThis.String(object.prevCumulativeBorrowRate)
        : isSet(object.prev_cumulative_borrow_rate)
        ? globalThis.String(object.prev_cumulative_borrow_rate)
        : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: EstimateYieldRequest): unknown {
    const obj: any = {};
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.prevCumulativeBorrowRate !== "") {
      obj.prevCumulativeBorrowRate = message.prevCumulativeBorrowRate;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EstimateYieldRequest>, I>>(base?: I): EstimateYieldRequest {
    return EstimateYieldRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EstimateYieldRequest>, I>>(object: I): EstimateYieldRequest {
    const message = createBaseEstimateYieldRequest();
    message.amount = object.amount ?? "";
    message.prevCumulativeBorrowRate = object.prevCumulativeBorrowRate ?? "";
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseEstimateYieldResponse(): EstimateYieldResponse {
  return { yieldEstimate: 0 };
}

export const EstimateYieldResponse: MessageFns<EstimateYieldResponse> = {
  encode(message: EstimateYieldResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.yieldEstimate !== 0) {
      writer.uint32(9).double(message.yieldEstimate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EstimateYieldResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEstimateYieldResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.yieldEstimate = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EstimateYieldResponse {
    return {
      yieldEstimate: isSet(object.yieldEstimate)
        ? globalThis.Number(object.yieldEstimate)
        : isSet(object.yield_estimate)
        ? globalThis.Number(object.yield_estimate)
        : 0,
    };
  },

  toJSON(message: EstimateYieldResponse): unknown {
    const obj: any = {};
    if (message.yieldEstimate !== 0) {
      obj.yieldEstimate = message.yieldEstimate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EstimateYieldResponse>, I>>(base?: I): EstimateYieldResponse {
    return EstimateYieldResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EstimateYieldResponse>, I>>(object: I): EstimateYieldResponse {
    const message = createBaseEstimateYieldResponse();
    message.yieldEstimate = object.yieldEstimate ?? 0;
    return message;
  },
};

function createBaseDepositRequest(): DepositRequest {
  return { amount: "", token: undefined };
}

export const DepositRequest: MessageFns<DepositRequest> = {
  encode(message: DepositRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== "") {
      writer.uint32(10).string(message.amount);
    }
    if (message.token !== undefined) {
      writer.uint32(16).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DepositRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDepositRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DepositRequest {
    return {
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: DepositRequest): unknown {
    const obj: any = {};
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DepositRequest>, I>>(base?: I): DepositRequest {
    return DepositRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DepositRequest>, I>>(object: I): DepositRequest {
    const message = createBaseDepositRequest();
    message.amount = object.amount ?? "";
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseBorrowRequest(): BorrowRequest {
  return { requestId: "", amount: "", token: undefined };
}

export const BorrowRequest: MessageFns<BorrowRequest> = {
  encode(message: BorrowRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (message.token !== undefined) {
      writer.uint32(24).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BorrowRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBorrowRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BorrowRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: BorrowRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BorrowRequest>, I>>(base?: I): BorrowRequest {
    return BorrowRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BorrowRequest>, I>>(object: I): BorrowRequest {
    const message = createBaseBorrowRequest();
    message.requestId = object.requestId ?? "";
    message.amount = object.amount ?? "";
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseRepayRequest(): RepayRequest {
  return { requestId: "", amount: "", token: undefined };
}

export const RepayRequest: MessageFns<RepayRequest> = {
  encode(message: RepayRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (message.token !== undefined) {
      writer.uint32(24).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RepayRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRepayRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RepayRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: RepayRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RepayRequest>, I>>(base?: I): RepayRequest {
    return RepayRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RepayRequest>, I>>(object: I): RepayRequest {
    const message = createBaseRepayRequest();
    message.requestId = object.requestId ?? "";
    message.amount = object.amount ?? "";
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseWithdrawRequest(): WithdrawRequest {
  return { amount: "", token: undefined };
}

export const WithdrawRequest: MessageFns<WithdrawRequest> = {
  encode(message: WithdrawRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== "") {
      writer.uint32(10).string(message.amount);
    }
    if (message.token !== undefined) {
      writer.uint32(16).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WithdrawRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWithdrawRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WithdrawRequest {
    return {
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: WithdrawRequest): unknown {
    const obj: any = {};
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WithdrawRequest>, I>>(base?: I): WithdrawRequest {
    return WithdrawRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WithdrawRequest>, I>>(object: I): WithdrawRequest {
    const message = createBaseWithdrawRequest();
    message.amount = object.amount ?? "";
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseDepositCollateralRequest(): DepositCollateralRequest {
  return { amount: "" };
}

export const DepositCollateralRequest: MessageFns<DepositCollateralRequest> = {
  encode(message: DepositCollateralRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== "") {
      writer.uint32(10).string(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DepositCollateralRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDepositCollateralRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DepositCollateralRequest {
    return { amount: isSet(object.amount) ? globalThis.String(object.amount) : "" };
  },

  toJSON(message: DepositCollateralRequest): unknown {
    const obj: any = {};
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DepositCollateralRequest>, I>>(base?: I): DepositCollateralRequest {
    return DepositCollateralRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DepositCollateralRequest>, I>>(object: I): DepositCollateralRequest {
    const message = createBaseDepositCollateralRequest();
    message.amount = object.amount ?? "";
    return message;
  },
};

function createBaseKaminoTx(): KaminoTx {
  return { amount: "", asset: "", txType: "", signature: "", txCost: 0, timeStamp: 0, requestId: undefined };
}

export const KaminoTx: MessageFns<KaminoTx> = {
  encode(message: KaminoTx, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amount !== "") {
      writer.uint32(10).string(message.amount);
    }
    if (message.asset !== "") {
      writer.uint32(18).string(message.asset);
    }
    if (message.txType !== "") {
      writer.uint32(26).string(message.txType);
    }
    if (message.signature !== "") {
      writer.uint32(34).string(message.signature);
    }
    if (message.txCost !== 0) {
      writer.uint32(41).double(message.txCost);
    }
    if (message.timeStamp !== 0) {
      writer.uint32(48).int64(message.timeStamp);
    }
    if (message.requestId !== undefined) {
      writer.uint32(58).string(message.requestId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KaminoTx {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKaminoTx();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.txType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.txCost = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timeStamp = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KaminoTx {
    return {
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
      txType: isSet(object.txType)
        ? globalThis.String(object.txType)
        : isSet(object.tx_type)
        ? globalThis.String(object.tx_type)
        : "",
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
      txCost: isSet(object.txCost)
        ? globalThis.Number(object.txCost)
        : isSet(object.tx_cost)
        ? globalThis.Number(object.tx_cost)
        : 0,
      timeStamp: isSet(object.timeStamp)
        ? globalThis.Number(object.timeStamp)
        : isSet(object.time_stamp)
        ? globalThis.Number(object.time_stamp)
        : 0,
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : undefined,
    };
  },

  toJSON(message: KaminoTx): unknown {
    const obj: any = {};
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    if (message.txType !== "") {
      obj.txType = message.txType;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    if (message.txCost !== 0) {
      obj.txCost = message.txCost;
    }
    if (message.timeStamp !== 0) {
      obj.timeStamp = Math.round(message.timeStamp);
    }
    if (message.requestId !== undefined) {
      obj.requestId = message.requestId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KaminoTx>, I>>(base?: I): KaminoTx {
    return KaminoTx.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KaminoTx>, I>>(object: I): KaminoTx {
    const message = createBaseKaminoTx();
    message.amount = object.amount ?? "";
    message.asset = object.asset ?? "";
    message.txType = object.txType ?? "";
    message.signature = object.signature ?? "";
    message.txCost = object.txCost ?? 0;
    message.timeStamp = object.timeStamp ?? 0;
    message.requestId = object.requestId ?? undefined;
    return message;
  },
};

export type KaminoDefinition = typeof KaminoDefinition;
export const KaminoDefinition = {
  name: "Kamino",
  fullName: "kamino.Kamino",
  methods: {
    getBorrowCapacity: {
      name: "GetBorrowCapacity",
      requestType: BorrowCapacityRequest as typeof BorrowCapacityRequest,
      requestStream: false,
      responseType: BorrowCapacityResponse as typeof BorrowCapacityResponse,
      responseStream: false,
      options: {},
    },
    getStats: {
      name: "GetStats",
      requestType: GetStatsRequest as typeof GetStatsRequest,
      requestStream: false,
      responseType: StatsResponse as typeof StatsResponse,
      responseStream: false,
      options: {},
    },
    refreshStats: {
      name: "RefreshStats",
      requestType: RefreshStatsRequest as typeof RefreshStatsRequest,
      requestStream: false,
      responseType: StatsResponse as typeof StatsResponse,
      responseStream: false,
      options: {},
    },
    getCumulativeBorrowRate: {
      name: "GetCumulativeBorrowRate",
      requestType: CbrRequest as typeof CbrRequest,
      requestStream: false,
      responseType: CbrResponse as typeof CbrResponse,
      responseStream: false,
      options: {},
    },
    estimateYield: {
      name: "EstimateYield",
      requestType: EstimateYieldRequest as typeof EstimateYieldRequest,
      requestStream: false,
      responseType: EstimateYieldResponse as typeof EstimateYieldResponse,
      responseStream: false,
      options: {},
    },
    deposit: {
      name: "Deposit",
      requestType: DepositRequest as typeof DepositRequest,
      requestStream: false,
      responseType: KaminoTx as typeof KaminoTx,
      responseStream: false,
      options: {},
    },
    borrow: {
      name: "Borrow",
      requestType: BorrowRequest as typeof BorrowRequest,
      requestStream: false,
      responseType: KaminoTx as typeof KaminoTx,
      responseStream: false,
      options: {},
    },
    repay: {
      name: "Repay",
      requestType: RepayRequest as typeof RepayRequest,
      requestStream: false,
      responseType: KaminoTx as typeof KaminoTx,
      responseStream: false,
      options: {},
    },
    withdraw: {
      name: "Withdraw",
      requestType: WithdrawRequest as typeof WithdrawRequest,
      requestStream: false,
      responseType: KaminoTx as typeof KaminoTx,
      responseStream: false,
      options: {},
    },
    depositCollateral: {
      name: "DepositCollateral",
      requestType: DepositCollateralRequest as typeof DepositCollateralRequest,
      requestStream: false,
      responseType: KaminoTx as typeof KaminoTx,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface KaminoServiceImplementation<CallContextExt = {}> {
  getBorrowCapacity(
    request: BorrowCapacityRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<BorrowCapacityResponse>>;
  getStats(request: GetStatsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<StatsResponse>>;
  refreshStats(
    request: RefreshStatsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<StatsResponse>>;
  getCumulativeBorrowRate(
    request: CbrRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<CbrResponse>>;
  estimateYield(
    request: EstimateYieldRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<EstimateYieldResponse>>;
  deposit(request: DepositRequest, context: CallContext & CallContextExt): Promise<DeepPartial<KaminoTx>>;
  borrow(request: BorrowRequest, context: CallContext & CallContextExt): Promise<DeepPartial<KaminoTx>>;
  repay(request: RepayRequest, context: CallContext & CallContextExt): Promise<DeepPartial<KaminoTx>>;
  withdraw(request: WithdrawRequest, context: CallContext & CallContextExt): Promise<DeepPartial<KaminoTx>>;
  depositCollateral(
    request: DepositCollateralRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<KaminoTx>>;
}

export interface KaminoClient<CallOptionsExt = {}> {
  getBorrowCapacity(
    request: DeepPartial<BorrowCapacityRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<BorrowCapacityResponse>;
  getStats(request: DeepPartial<GetStatsRequest>, options?: CallOptions & CallOptionsExt): Promise<StatsResponse>;
  refreshStats(
    request: DeepPartial<RefreshStatsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<StatsResponse>;
  getCumulativeBorrowRate(
    request: DeepPartial<CbrRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<CbrResponse>;
  estimateYield(
    request: DeepPartial<EstimateYieldRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<EstimateYieldResponse>;
  deposit(request: DeepPartial<DepositRequest>, options?: CallOptions & CallOptionsExt): Promise<KaminoTx>;
  borrow(request: DeepPartial<BorrowRequest>, options?: CallOptions & CallOptionsExt): Promise<KaminoTx>;
  repay(request: DeepPartial<RepayRequest>, options?: CallOptions & CallOptionsExt): Promise<KaminoTx>;
  withdraw(request: DeepPartial<WithdrawRequest>, options?: CallOptions & CallOptionsExt): Promise<KaminoTx>;
  depositCollateral(
    request: DeepPartial<DepositCollateralRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<KaminoTx>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
