// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: orbit.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { DecodeEventRequest, EventData, Token, tokenFromJSON, tokenToJSON } from "./base";

export const protobufPackage = "orbit";

export interface GetPdaRequest {
  key: string;
}

export interface PdaResponse {
  pda: string;
  key: string;
  type: string;
}

export interface OrderData {
  orderId: string;
  amount: string;
  address: string;
}

export interface CollectRequest {
  orderId: string;
  vaultId: string;
  userId: string;
  address: string;
  amount: string;
  token?: Token | undefined;
}

export interface DisburseRequest {
  requestId: string;
  userId: string;
  address: string;
  amount: string;
  orderId?: string | undefined;
  token?: Token | undefined;
}

export interface TxResponse {
  orderId: string;
  signature: string;
  position: number;
}

export interface LPRequest {
  userId: string;
  address: string;
  memo?: string | undefined;
}

export interface LPState {
  status: string;
  pda: string;
  txPda?: string | undefined;
}

function createBaseGetPdaRequest(): GetPdaRequest {
  return { key: "" };
}

export const GetPdaRequest: MessageFns<GetPdaRequest> = {
  encode(message: GetPdaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPdaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPdaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPdaRequest {
    return { key: isSet(object.key) ? globalThis.String(object.key) : "" };
  },

  toJSON(message: GetPdaRequest): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPdaRequest>, I>>(base?: I): GetPdaRequest {
    return GetPdaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPdaRequest>, I>>(object: I): GetPdaRequest {
    const message = createBaseGetPdaRequest();
    message.key = object.key ?? "";
    return message;
  },
};

function createBasePdaResponse(): PdaResponse {
  return { pda: "", key: "", type: "" };
}

export const PdaResponse: MessageFns<PdaResponse> = {
  encode(message: PdaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pda !== "") {
      writer.uint32(10).string(message.pda);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PdaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePdaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pda = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PdaResponse {
    return {
      pda: isSet(object.pda) ? globalThis.String(object.pda) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
    };
  },

  toJSON(message: PdaResponse): unknown {
    const obj: any = {};
    if (message.pda !== "") {
      obj.pda = message.pda;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PdaResponse>, I>>(base?: I): PdaResponse {
    return PdaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PdaResponse>, I>>(object: I): PdaResponse {
    const message = createBasePdaResponse();
    message.pda = object.pda ?? "";
    message.key = object.key ?? "";
    message.type = object.type ?? "";
    return message;
  },
};

function createBaseOrderData(): OrderData {
  return { orderId: "", amount: "", address: "" };
}

export const OrderData: MessageFns<OrderData> = {
  encode(message: OrderData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderData {
    return {
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
    };
  },

  toJSON(message: OrderData): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderData>, I>>(base?: I): OrderData {
    return OrderData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderData>, I>>(object: I): OrderData {
    const message = createBaseOrderData();
    message.orderId = object.orderId ?? "";
    message.amount = object.amount ?? "";
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseCollectRequest(): CollectRequest {
  return { orderId: "", vaultId: "", userId: "", address: "", amount: "", token: undefined };
}

export const CollectRequest: MessageFns<CollectRequest> = {
  encode(message: CollectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.vaultId !== "") {
      writer.uint32(18).string(message.vaultId);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.address !== "") {
      writer.uint32(34).string(message.address);
    }
    if (message.amount !== "") {
      writer.uint32(42).string(message.amount);
    }
    if (message.token !== undefined) {
      writer.uint32(48).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CollectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCollectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CollectRequest {
    return {
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : "",
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: CollectRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CollectRequest>, I>>(base?: I): CollectRequest {
    return CollectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CollectRequest>, I>>(object: I): CollectRequest {
    const message = createBaseCollectRequest();
    message.orderId = object.orderId ?? "";
    message.vaultId = object.vaultId ?? "";
    message.userId = object.userId ?? "";
    message.address = object.address ?? "";
    message.amount = object.amount ?? "";
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseDisburseRequest(): DisburseRequest {
  return { requestId: "", userId: "", address: "", amount: "", orderId: undefined, token: undefined };
}

export const DisburseRequest: MessageFns<DisburseRequest> = {
  encode(message: DisburseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    if (message.amount !== "") {
      writer.uint32(34).string(message.amount);
    }
    if (message.orderId !== undefined) {
      writer.uint32(42).string(message.orderId);
    }
    if (message.token !== undefined) {
      writer.uint32(48).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisburseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisburseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DisburseRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : undefined,
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: DisburseRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.orderId !== undefined) {
      obj.orderId = message.orderId;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DisburseRequest>, I>>(base?: I): DisburseRequest {
    return DisburseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DisburseRequest>, I>>(object: I): DisburseRequest {
    const message = createBaseDisburseRequest();
    message.requestId = object.requestId ?? "";
    message.userId = object.userId ?? "";
    message.address = object.address ?? "";
    message.amount = object.amount ?? "";
    message.orderId = object.orderId ?? undefined;
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseTxResponse(): TxResponse {
  return { orderId: "", signature: "", position: 0 };
}

export const TxResponse: MessageFns<TxResponse> = {
  encode(message: TxResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.signature !== "") {
      writer.uint32(18).string(message.signature);
    }
    if (message.position !== 0) {
      writer.uint32(24).uint32(message.position);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.position = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxResponse {
    return {
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : "",
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
    };
  },

  toJSON(message: TxResponse): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxResponse>, I>>(base?: I): TxResponse {
    return TxResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxResponse>, I>>(object: I): TxResponse {
    const message = createBaseTxResponse();
    message.orderId = object.orderId ?? "";
    message.signature = object.signature ?? "";
    message.position = object.position ?? 0;
    return message;
  },
};

function createBaseLPRequest(): LPRequest {
  return { userId: "", address: "", memo: undefined };
}

export const LPRequest: MessageFns<LPRequest> = {
  encode(message: LPRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.address !== "") {
      writer.uint32(18).string(message.address);
    }
    if (message.memo !== undefined) {
      writer.uint32(26).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LPRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLPRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LPRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
    };
  },

  toJSON(message: LPRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LPRequest>, I>>(base?: I): LPRequest {
    return LPRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LPRequest>, I>>(object: I): LPRequest {
    const message = createBaseLPRequest();
    message.userId = object.userId ?? "";
    message.address = object.address ?? "";
    message.memo = object.memo ?? undefined;
    return message;
  },
};

function createBaseLPState(): LPState {
  return { status: "", pda: "", txPda: undefined };
}

export const LPState: MessageFns<LPState> = {
  encode(message: LPState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.pda !== "") {
      writer.uint32(18).string(message.pda);
    }
    if (message.txPda !== undefined) {
      writer.uint32(26).string(message.txPda);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LPState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLPState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pda = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.txPda = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LPState {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      pda: isSet(object.pda) ? globalThis.String(object.pda) : "",
      txPda: isSet(object.txPda)
        ? globalThis.String(object.txPda)
        : isSet(object.tx_pda)
        ? globalThis.String(object.tx_pda)
        : undefined,
    };
  },

  toJSON(message: LPState): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.pda !== "") {
      obj.pda = message.pda;
    }
    if (message.txPda !== undefined) {
      obj.txPda = message.txPda;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LPState>, I>>(base?: I): LPState {
    return LPState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LPState>, I>>(object: I): LPState {
    const message = createBaseLPState();
    message.status = object.status ?? "";
    message.pda = object.pda ?? "";
    message.txPda = object.txPda ?? undefined;
    return message;
  },
};

export type OrbitDefinition = typeof OrbitDefinition;
export const OrbitDefinition = {
  name: "Orbit",
  fullName: "orbit.Orbit",
  methods: {
    getVaultPda: {
      name: "GetVaultPda",
      requestType: GetPdaRequest as typeof GetPdaRequest,
      requestStream: false,
      responseType: PdaResponse as typeof PdaResponse,
      responseStream: false,
      options: {},
    },
    getOrderPda: {
      name: "GetOrderPda",
      requestType: GetPdaRequest as typeof GetPdaRequest,
      requestStream: false,
      responseType: PdaResponse as typeof PdaResponse,
      responseStream: false,
      options: {},
    },
    readOrderPda: {
      name: "ReadOrderPda",
      requestType: GetPdaRequest as typeof GetPdaRequest,
      requestStream: false,
      responseType: OrderData as typeof OrderData,
      responseStream: false,
      options: {},
    },
    collect: {
      name: "Collect",
      requestType: CollectRequest as typeof CollectRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    disburse: {
      name: "Disburse",
      requestType: DisburseRequest as typeof DisburseRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    decodeEvent: {
      name: "DecodeEvent",
      requestType: DecodeEventRequest as typeof DecodeEventRequest,
      requestStream: false,
      responseType: EventData as typeof EventData,
      responseStream: false,
      options: {},
    },
    verifyLP: {
      name: "VerifyLP",
      requestType: LPRequest as typeof LPRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    whitelistLP: {
      name: "WhitelistLP",
      requestType: LPRequest as typeof LPRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    revokeLP: {
      name: "RevokeLP",
      requestType: LPRequest as typeof LPRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface OrbitServiceImplementation<CallContextExt = {}> {
  getVaultPda(request: GetPdaRequest, context: CallContext & CallContextExt): Promise<DeepPartial<PdaResponse>>;
  getOrderPda(request: GetPdaRequest, context: CallContext & CallContextExt): Promise<DeepPartial<PdaResponse>>;
  readOrderPda(request: GetPdaRequest, context: CallContext & CallContextExt): Promise<DeepPartial<OrderData>>;
  collect(request: CollectRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
  disburse(request: DisburseRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
  decodeEvent(request: DecodeEventRequest, context: CallContext & CallContextExt): Promise<DeepPartial<EventData>>;
  verifyLP(request: LPRequest, context: CallContext & CallContextExt): Promise<DeepPartial<LPState>>;
  whitelistLP(request: LPRequest, context: CallContext & CallContextExt): Promise<DeepPartial<LPState>>;
  revokeLP(request: LPRequest, context: CallContext & CallContextExt): Promise<DeepPartial<LPState>>;
}

export interface OrbitClient<CallOptionsExt = {}> {
  getVaultPda(request: DeepPartial<GetPdaRequest>, options?: CallOptions & CallOptionsExt): Promise<PdaResponse>;
  getOrderPda(request: DeepPartial<GetPdaRequest>, options?: CallOptions & CallOptionsExt): Promise<PdaResponse>;
  readOrderPda(request: DeepPartial<GetPdaRequest>, options?: CallOptions & CallOptionsExt): Promise<OrderData>;
  collect(request: DeepPartial<CollectRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
  disburse(request: DeepPartial<DisburseRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
  decodeEvent(request: DeepPartial<DecodeEventRequest>, options?: CallOptions & CallOptionsExt): Promise<EventData>;
  verifyLP(request: DeepPartial<LPRequest>, options?: CallOptions & CallOptionsExt): Promise<LPState>;
  whitelistLP(request: DeepPartial<LPRequest>, options?: CallOptions & CallOptionsExt): Promise<LPState>;
  revokeLP(request: DeepPartial<LPRequest>, options?: CallOptions & CallOptionsExt): Promise<LPState>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
