// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.36.0
// source: orbit.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { DecodeEventRequest, EventData, Token, tokenFromJSON, tokenToJSON } from "./base";

export const protobufPackage = "orbit";

export enum UserType {
  LP = 0,
  NCW = 1,
  ICV = 2,
  UNRECOGNIZED = -1,
}

export function userTypeFromJSON(object: any): UserType {
  switch (object) {
    case 0:
    case "LP":
      return UserType.LP;
    case 1:
    case "NCW":
      return UserType.NCW;
    case 2:
    case "ICV":
      return UserType.ICV;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UserType.UNRECOGNIZED;
  }
}

export function userTypeToJSON(object: UserType): string {
  switch (object) {
    case UserType.LP:
      return "LP";
    case UserType.NCW:
      return "NCW";
    case UserType.ICV:
      return "ICV";
    case UserType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum WhitelistAction {
  ADD = 0,
  REMOVE = 1,
  UNRECOGNIZED = -1,
}

export function whitelistActionFromJSON(object: any): WhitelistAction {
  switch (object) {
    case 0:
    case "ADD":
      return WhitelistAction.ADD;
    case 1:
    case "REMOVE":
      return WhitelistAction.REMOVE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WhitelistAction.UNRECOGNIZED;
  }
}

export function whitelistActionToJSON(object: WhitelistAction): string {
  switch (object) {
    case WhitelistAction.ADD:
      return "ADD";
    case WhitelistAction.REMOVE:
      return "REMOVE";
    case WhitelistAction.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface GetPdaRequest {
  key: string;
}

export interface PdaResponse {
  pda: string;
  key: string;
  type: string;
}

export interface OrderData {
  orderId: string;
  amount: string;
  address: string;
}

export interface CollectRequest {
  orderId: string;
  vaultId: string;
  userId: string;
  address: string;
  amount: string;
  token?: Token | undefined;
}

export interface DisburseRequest {
  requestId: string;
  userId: string;
  address: string;
  amount: string;
  orderId?: string | undefined;
  token?: Token | undefined;
}

export interface TxResponse {
  orderId: string;
  signature: string;
  position: number;
}

export interface LPState {
  status: string;
  pda: string;
  txPda?: string | undefined;
}

/**
 * VerifyUser: read-only check – returns LPState for the user's Record PDA.
 * status = "active" when the user record exists, "unavailable" otherwise.
 */
export interface VerifyUserRequest {
  userId: string;
}

export interface RegisterUserRequest {
  userId: string;
  userType: UserType;
  /**
   * 1 to 3 authorised wallet addresses. Missing slots are padded with the
   * system public key (11111111111111111111111111111111) on-chain.
   */
  wallets: string[];
  /** Unix timestamp string. Omit → i64::MAX (no lock). */
  cliffPeriod?:
    | string
    | undefined;
  /** u32 cap. Omit → u32::MAX (uncapped). */
  maxDeposit?: number | undefined;
  memo?: string | undefined;
}

export interface RevokeRequest {
  /** One or more Orbit PDA public-key strings to close via remainingAccounts. */
  accounts: string[];
  memo?: string | undefined;
}

export interface UpdatePartnerWhitelistRequest {
  userId: string;
  action: WhitelistAction;
  partnerId: number;
  memo?: string | undefined;
}

export interface UpdateWalletsRequest {
  userId: string;
  /**
   * 1 to 3 replacement wallet addresses. Missing slots are padded with the
   * system public key (11111111111111111111111111111111) on-chain.
   */
  wallets: string[];
  memo?: string | undefined;
}

export interface UpdateMaxPrincipalRequest {
  userId: string;
  maxDeposit: number;
  memo?: string | undefined;
}

export interface UpdateCliffPeriodRequest {
  userId: string;
  /** Unix timestamp string. Omit → preserves existing cliff on-chain. */
  cliffPeriod?: string | undefined;
  memo?: string | undefined;
}

export interface ApproveWithdrawRequest {
  userId: string;
  token?: Token | undefined;
  memo?: string | undefined;
}

export interface RejectWithdrawRequest {
  userId: string;
  memo?: string | undefined;
}

function createBaseGetPdaRequest(): GetPdaRequest {
  return { key: "" };
}

export const GetPdaRequest: MessageFns<GetPdaRequest> = {
  encode(message: GetPdaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPdaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPdaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPdaRequest {
    return { key: isSet(object.key) ? globalThis.String(object.key) : "" };
  },

  toJSON(message: GetPdaRequest): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPdaRequest>, I>>(base?: I): GetPdaRequest {
    return GetPdaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPdaRequest>, I>>(object: I): GetPdaRequest {
    const message = createBaseGetPdaRequest();
    message.key = object.key ?? "";
    return message;
  },
};

function createBasePdaResponse(): PdaResponse {
  return { pda: "", key: "", type: "" };
}

export const PdaResponse: MessageFns<PdaResponse> = {
  encode(message: PdaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pda !== "") {
      writer.uint32(10).string(message.pda);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PdaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePdaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pda = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PdaResponse {
    return {
      pda: isSet(object.pda) ? globalThis.String(object.pda) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
    };
  },

  toJSON(message: PdaResponse): unknown {
    const obj: any = {};
    if (message.pda !== "") {
      obj.pda = message.pda;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PdaResponse>, I>>(base?: I): PdaResponse {
    return PdaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PdaResponse>, I>>(object: I): PdaResponse {
    const message = createBasePdaResponse();
    message.pda = object.pda ?? "";
    message.key = object.key ?? "";
    message.type = object.type ?? "";
    return message;
  },
};

function createBaseOrderData(): OrderData {
  return { orderId: "", amount: "", address: "" };
}

export const OrderData: MessageFns<OrderData> = {
  encode(message: OrderData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.amount !== "") {
      writer.uint32(18).string(message.amount);
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrderData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderData {
    return {
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
    };
  },

  toJSON(message: OrderData): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderData>, I>>(base?: I): OrderData {
    return OrderData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderData>, I>>(object: I): OrderData {
    const message = createBaseOrderData();
    message.orderId = object.orderId ?? "";
    message.amount = object.amount ?? "";
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseCollectRequest(): CollectRequest {
  return { orderId: "", vaultId: "", userId: "", address: "", amount: "", token: undefined };
}

export const CollectRequest: MessageFns<CollectRequest> = {
  encode(message: CollectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.vaultId !== "") {
      writer.uint32(18).string(message.vaultId);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.address !== "") {
      writer.uint32(34).string(message.address);
    }
    if (message.amount !== "") {
      writer.uint32(42).string(message.amount);
    }
    if (message.token !== undefined) {
      writer.uint32(48).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CollectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCollectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CollectRequest {
    return {
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : "",
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: CollectRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CollectRequest>, I>>(base?: I): CollectRequest {
    return CollectRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CollectRequest>, I>>(object: I): CollectRequest {
    const message = createBaseCollectRequest();
    message.orderId = object.orderId ?? "";
    message.vaultId = object.vaultId ?? "";
    message.userId = object.userId ?? "";
    message.address = object.address ?? "";
    message.amount = object.amount ?? "";
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseDisburseRequest(): DisburseRequest {
  return { requestId: "", userId: "", address: "", amount: "", orderId: undefined, token: undefined };
}

export const DisburseRequest: MessageFns<DisburseRequest> = {
  encode(message: DisburseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    if (message.amount !== "") {
      writer.uint32(34).string(message.amount);
    }
    if (message.orderId !== undefined) {
      writer.uint32(42).string(message.orderId);
    }
    if (message.token !== undefined) {
      writer.uint32(48).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisburseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisburseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DisburseRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : undefined,
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: DisburseRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.orderId !== undefined) {
      obj.orderId = message.orderId;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DisburseRequest>, I>>(base?: I): DisburseRequest {
    return DisburseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DisburseRequest>, I>>(object: I): DisburseRequest {
    const message = createBaseDisburseRequest();
    message.requestId = object.requestId ?? "";
    message.userId = object.userId ?? "";
    message.address = object.address ?? "";
    message.amount = object.amount ?? "";
    message.orderId = object.orderId ?? undefined;
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseTxResponse(): TxResponse {
  return { orderId: "", signature: "", position: 0 };
}

export const TxResponse: MessageFns<TxResponse> = {
  encode(message: TxResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.signature !== "") {
      writer.uint32(18).string(message.signature);
    }
    if (message.position !== 0) {
      writer.uint32(24).uint32(message.position);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.position = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxResponse {
    return {
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : "",
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
    };
  },

  toJSON(message: TxResponse): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxResponse>, I>>(base?: I): TxResponse {
    return TxResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxResponse>, I>>(object: I): TxResponse {
    const message = createBaseTxResponse();
    message.orderId = object.orderId ?? "";
    message.signature = object.signature ?? "";
    message.position = object.position ?? 0;
    return message;
  },
};

function createBaseLPState(): LPState {
  return { status: "", pda: "", txPda: undefined };
}

export const LPState: MessageFns<LPState> = {
  encode(message: LPState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.pda !== "") {
      writer.uint32(18).string(message.pda);
    }
    if (message.txPda !== undefined) {
      writer.uint32(26).string(message.txPda);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LPState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLPState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pda = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.txPda = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LPState {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      pda: isSet(object.pda) ? globalThis.String(object.pda) : "",
      txPda: isSet(object.txPda)
        ? globalThis.String(object.txPda)
        : isSet(object.tx_pda)
        ? globalThis.String(object.tx_pda)
        : undefined,
    };
  },

  toJSON(message: LPState): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.pda !== "") {
      obj.pda = message.pda;
    }
    if (message.txPda !== undefined) {
      obj.txPda = message.txPda;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LPState>, I>>(base?: I): LPState {
    return LPState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LPState>, I>>(object: I): LPState {
    const message = createBaseLPState();
    message.status = object.status ?? "";
    message.pda = object.pda ?? "";
    message.txPda = object.txPda ?? undefined;
    return message;
  },
};

function createBaseVerifyUserRequest(): VerifyUserRequest {
  return { userId: "" };
}

export const VerifyUserRequest: MessageFns<VerifyUserRequest> = {
  encode(message: VerifyUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VerifyUserRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
    };
  },

  toJSON(message: VerifyUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VerifyUserRequest>, I>>(base?: I): VerifyUserRequest {
    return VerifyUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VerifyUserRequest>, I>>(object: I): VerifyUserRequest {
    const message = createBaseVerifyUserRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseRegisterUserRequest(): RegisterUserRequest {
  return { userId: "", userType: 0, wallets: [], cliffPeriod: undefined, maxDeposit: undefined, memo: undefined };
}

export const RegisterUserRequest: MessageFns<RegisterUserRequest> = {
  encode(message: RegisterUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.userType !== 0) {
      writer.uint32(16).int32(message.userType);
    }
    for (const v of message.wallets) {
      writer.uint32(26).string(v!);
    }
    if (message.cliffPeriod !== undefined) {
      writer.uint32(34).string(message.cliffPeriod);
    }
    if (message.maxDeposit !== undefined) {
      writer.uint32(40).uint32(message.maxDeposit);
    }
    if (message.memo !== undefined) {
      writer.uint32(50).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.wallets.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cliffPeriod = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.maxDeposit = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterUserRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      userType: isSet(object.userType)
        ? userTypeFromJSON(object.userType)
        : isSet(object.user_type)
        ? userTypeFromJSON(object.user_type)
        : 0,
      wallets: globalThis.Array.isArray(object?.wallets) ? object.wallets.map((e: any) => globalThis.String(e)) : [],
      cliffPeriod: isSet(object.cliffPeriod)
        ? globalThis.String(object.cliffPeriod)
        : isSet(object.cliff_period)
        ? globalThis.String(object.cliff_period)
        : undefined,
      maxDeposit: isSet(object.maxDeposit)
        ? globalThis.Number(object.maxDeposit)
        : isSet(object.max_deposit)
        ? globalThis.Number(object.max_deposit)
        : undefined,
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
    };
  },

  toJSON(message: RegisterUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.userType !== 0) {
      obj.userType = userTypeToJSON(message.userType);
    }
    if (message.wallets?.length) {
      obj.wallets = message.wallets;
    }
    if (message.cliffPeriod !== undefined) {
      obj.cliffPeriod = message.cliffPeriod;
    }
    if (message.maxDeposit !== undefined) {
      obj.maxDeposit = Math.round(message.maxDeposit);
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterUserRequest>, I>>(base?: I): RegisterUserRequest {
    return RegisterUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterUserRequest>, I>>(object: I): RegisterUserRequest {
    const message = createBaseRegisterUserRequest();
    message.userId = object.userId ?? "";
    message.userType = object.userType ?? 0;
    message.wallets = object.wallets?.map((e) => e) || [];
    message.cliffPeriod = object.cliffPeriod ?? undefined;
    message.maxDeposit = object.maxDeposit ?? undefined;
    message.memo = object.memo ?? undefined;
    return message;
  },
};

function createBaseRevokeRequest(): RevokeRequest {
  return { accounts: [], memo: undefined };
}

export const RevokeRequest: MessageFns<RevokeRequest> = {
  encode(message: RevokeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.accounts) {
      writer.uint32(10).string(v!);
    }
    if (message.memo !== undefined) {
      writer.uint32(18).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RevokeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRevokeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.accounts.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RevokeRequest {
    return {
      accounts: globalThis.Array.isArray(object?.accounts) ? object.accounts.map((e: any) => globalThis.String(e)) : [],
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
    };
  },

  toJSON(message: RevokeRequest): unknown {
    const obj: any = {};
    if (message.accounts?.length) {
      obj.accounts = message.accounts;
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RevokeRequest>, I>>(base?: I): RevokeRequest {
    return RevokeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RevokeRequest>, I>>(object: I): RevokeRequest {
    const message = createBaseRevokeRequest();
    message.accounts = object.accounts?.map((e) => e) || [];
    message.memo = object.memo ?? undefined;
    return message;
  },
};

function createBaseUpdatePartnerWhitelistRequest(): UpdatePartnerWhitelistRequest {
  return { userId: "", action: 0, partnerId: 0, memo: undefined };
}

export const UpdatePartnerWhitelistRequest: MessageFns<UpdatePartnerWhitelistRequest> = {
  encode(message: UpdatePartnerWhitelistRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.action !== 0) {
      writer.uint32(16).int32(message.action);
    }
    if (message.partnerId !== 0) {
      writer.uint32(24).uint32(message.partnerId);
    }
    if (message.memo !== undefined) {
      writer.uint32(34).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdatePartnerWhitelistRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePartnerWhitelistRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.action = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.partnerId = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePartnerWhitelistRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      action: isSet(object.action) ? whitelistActionFromJSON(object.action) : 0,
      partnerId: isSet(object.partnerId)
        ? globalThis.Number(object.partnerId)
        : isSet(object.partner_id)
        ? globalThis.Number(object.partner_id)
        : 0,
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
    };
  },

  toJSON(message: UpdatePartnerWhitelistRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.action !== 0) {
      obj.action = whitelistActionToJSON(message.action);
    }
    if (message.partnerId !== 0) {
      obj.partnerId = Math.round(message.partnerId);
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdatePartnerWhitelistRequest>, I>>(base?: I): UpdatePartnerWhitelistRequest {
    return UpdatePartnerWhitelistRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdatePartnerWhitelistRequest>, I>>(
    object: I,
  ): UpdatePartnerWhitelistRequest {
    const message = createBaseUpdatePartnerWhitelistRequest();
    message.userId = object.userId ?? "";
    message.action = object.action ?? 0;
    message.partnerId = object.partnerId ?? 0;
    message.memo = object.memo ?? undefined;
    return message;
  },
};

function createBaseUpdateWalletsRequest(): UpdateWalletsRequest {
  return { userId: "", wallets: [], memo: undefined };
}

export const UpdateWalletsRequest: MessageFns<UpdateWalletsRequest> = {
  encode(message: UpdateWalletsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    for (const v of message.wallets) {
      writer.uint32(18).string(v!);
    }
    if (message.memo !== undefined) {
      writer.uint32(26).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateWalletsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateWalletsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.wallets.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateWalletsRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      wallets: globalThis.Array.isArray(object?.wallets) ? object.wallets.map((e: any) => globalThis.String(e)) : [],
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
    };
  },

  toJSON(message: UpdateWalletsRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.wallets?.length) {
      obj.wallets = message.wallets;
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateWalletsRequest>, I>>(base?: I): UpdateWalletsRequest {
    return UpdateWalletsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateWalletsRequest>, I>>(object: I): UpdateWalletsRequest {
    const message = createBaseUpdateWalletsRequest();
    message.userId = object.userId ?? "";
    message.wallets = object.wallets?.map((e) => e) || [];
    message.memo = object.memo ?? undefined;
    return message;
  },
};

function createBaseUpdateMaxPrincipalRequest(): UpdateMaxPrincipalRequest {
  return { userId: "", maxDeposit: 0, memo: undefined };
}

export const UpdateMaxPrincipalRequest: MessageFns<UpdateMaxPrincipalRequest> = {
  encode(message: UpdateMaxPrincipalRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.maxDeposit !== 0) {
      writer.uint32(16).uint32(message.maxDeposit);
    }
    if (message.memo !== undefined) {
      writer.uint32(26).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMaxPrincipalRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMaxPrincipalRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.maxDeposit = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMaxPrincipalRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      maxDeposit: isSet(object.maxDeposit)
        ? globalThis.Number(object.maxDeposit)
        : isSet(object.max_deposit)
        ? globalThis.Number(object.max_deposit)
        : 0,
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
    };
  },

  toJSON(message: UpdateMaxPrincipalRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.maxDeposit !== 0) {
      obj.maxDeposit = Math.round(message.maxDeposit);
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateMaxPrincipalRequest>, I>>(base?: I): UpdateMaxPrincipalRequest {
    return UpdateMaxPrincipalRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateMaxPrincipalRequest>, I>>(object: I): UpdateMaxPrincipalRequest {
    const message = createBaseUpdateMaxPrincipalRequest();
    message.userId = object.userId ?? "";
    message.maxDeposit = object.maxDeposit ?? 0;
    message.memo = object.memo ?? undefined;
    return message;
  },
};

function createBaseUpdateCliffPeriodRequest(): UpdateCliffPeriodRequest {
  return { userId: "", cliffPeriod: undefined, memo: undefined };
}

export const UpdateCliffPeriodRequest: MessageFns<UpdateCliffPeriodRequest> = {
  encode(message: UpdateCliffPeriodRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.cliffPeriod !== undefined) {
      writer.uint32(18).string(message.cliffPeriod);
    }
    if (message.memo !== undefined) {
      writer.uint32(26).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateCliffPeriodRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateCliffPeriodRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cliffPeriod = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateCliffPeriodRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      cliffPeriod: isSet(object.cliffPeriod)
        ? globalThis.String(object.cliffPeriod)
        : isSet(object.cliff_period)
        ? globalThis.String(object.cliff_period)
        : undefined,
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
    };
  },

  toJSON(message: UpdateCliffPeriodRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.cliffPeriod !== undefined) {
      obj.cliffPeriod = message.cliffPeriod;
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateCliffPeriodRequest>, I>>(base?: I): UpdateCliffPeriodRequest {
    return UpdateCliffPeriodRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateCliffPeriodRequest>, I>>(object: I): UpdateCliffPeriodRequest {
    const message = createBaseUpdateCliffPeriodRequest();
    message.userId = object.userId ?? "";
    message.cliffPeriod = object.cliffPeriod ?? undefined;
    message.memo = object.memo ?? undefined;
    return message;
  },
};

function createBaseApproveWithdrawRequest(): ApproveWithdrawRequest {
  return { userId: "", token: undefined, memo: undefined };
}

export const ApproveWithdrawRequest: MessageFns<ApproveWithdrawRequest> = {
  encode(message: ApproveWithdrawRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.token !== undefined) {
      writer.uint32(16).int32(message.token);
    }
    if (message.memo !== undefined) {
      writer.uint32(26).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApproveWithdrawRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApproveWithdrawRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApproveWithdrawRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
    };
  },

  toJSON(message: ApproveWithdrawRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApproveWithdrawRequest>, I>>(base?: I): ApproveWithdrawRequest {
    return ApproveWithdrawRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApproveWithdrawRequest>, I>>(object: I): ApproveWithdrawRequest {
    const message = createBaseApproveWithdrawRequest();
    message.userId = object.userId ?? "";
    message.token = object.token ?? undefined;
    message.memo = object.memo ?? undefined;
    return message;
  },
};

function createBaseRejectWithdrawRequest(): RejectWithdrawRequest {
  return { userId: "", memo: undefined };
}

export const RejectWithdrawRequest: MessageFns<RejectWithdrawRequest> = {
  encode(message: RejectWithdrawRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.memo !== undefined) {
      writer.uint32(18).string(message.memo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RejectWithdrawRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRejectWithdrawRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.memo = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RejectWithdrawRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      memo: isSet(object.memo) ? globalThis.String(object.memo) : undefined,
    };
  },

  toJSON(message: RejectWithdrawRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.memo !== undefined) {
      obj.memo = message.memo;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RejectWithdrawRequest>, I>>(base?: I): RejectWithdrawRequest {
    return RejectWithdrawRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RejectWithdrawRequest>, I>>(object: I): RejectWithdrawRequest {
    const message = createBaseRejectWithdrawRequest();
    message.userId = object.userId ?? "";
    message.memo = object.memo ?? undefined;
    return message;
  },
};

export type OrbitDefinition = typeof OrbitDefinition;
export const OrbitDefinition = {
  name: "Orbit",
  fullName: "orbit.Orbit",
  methods: {
    getVaultPda: {
      name: "GetVaultPda",
      requestType: GetPdaRequest as typeof GetPdaRequest,
      requestStream: false,
      responseType: PdaResponse as typeof PdaResponse,
      responseStream: false,
      options: {},
    },
    getOrderPda: {
      name: "GetOrderPda",
      requestType: GetPdaRequest as typeof GetPdaRequest,
      requestStream: false,
      responseType: PdaResponse as typeof PdaResponse,
      responseStream: false,
      options: {},
    },
    readOrderPda: {
      name: "ReadOrderPda",
      requestType: GetPdaRequest as typeof GetPdaRequest,
      requestStream: false,
      responseType: OrderData as typeof OrderData,
      responseStream: false,
      options: {},
    },
    collect: {
      name: "Collect",
      requestType: CollectRequest as typeof CollectRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    disburse: {
      name: "Disburse",
      requestType: DisburseRequest as typeof DisburseRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    decodeEvent: {
      name: "DecodeEvent",
      requestType: DecodeEventRequest as typeof DecodeEventRequest,
      requestStream: false,
      responseType: EventData as typeof EventData,
      responseStream: false,
      options: {},
    },
    /** ── LP / user-management (admin-signed, published via Squads) ──────────── */
    verifyUser: {
      name: "VerifyUser",
      requestType: VerifyUserRequest as typeof VerifyUserRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    registerUser: {
      name: "RegisterUser",
      requestType: RegisterUserRequest as typeof RegisterUserRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    revokeLP: {
      name: "RevokeLP",
      requestType: RevokeRequest as typeof RevokeRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    updatePartnerWhitelist: {
      name: "UpdatePartnerWhitelist",
      requestType: UpdatePartnerWhitelistRequest as typeof UpdatePartnerWhitelistRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    updateWallets: {
      name: "UpdateWallets",
      requestType: UpdateWalletsRequest as typeof UpdateWalletsRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    updateMaxPrincipal: {
      name: "UpdateMaxPrincipal",
      requestType: UpdateMaxPrincipalRequest as typeof UpdateMaxPrincipalRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    updateCliffPeriod: {
      name: "UpdateCliffPeriod",
      requestType: UpdateCliffPeriodRequest as typeof UpdateCliffPeriodRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    approveWithdraw: {
      name: "ApproveWithdraw",
      requestType: ApproveWithdrawRequest as typeof ApproveWithdrawRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
    rejectWithdraw: {
      name: "RejectWithdraw",
      requestType: RejectWithdrawRequest as typeof RejectWithdrawRequest,
      requestStream: false,
      responseType: LPState as typeof LPState,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface OrbitServiceImplementation<CallContextExt = {}> {
  getVaultPda(request: GetPdaRequest, context: CallContext & CallContextExt): Promise<DeepPartial<PdaResponse>>;
  getOrderPda(request: GetPdaRequest, context: CallContext & CallContextExt): Promise<DeepPartial<PdaResponse>>;
  readOrderPda(request: GetPdaRequest, context: CallContext & CallContextExt): Promise<DeepPartial<OrderData>>;
  collect(request: CollectRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
  disburse(request: DisburseRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
  decodeEvent(request: DecodeEventRequest, context: CallContext & CallContextExt): Promise<DeepPartial<EventData>>;
  /** ── LP / user-management (admin-signed, published via Squads) ──────────── */
  verifyUser(request: VerifyUserRequest, context: CallContext & CallContextExt): Promise<DeepPartial<LPState>>;
  registerUser(request: RegisterUserRequest, context: CallContext & CallContextExt): Promise<DeepPartial<LPState>>;
  revokeLP(request: RevokeRequest, context: CallContext & CallContextExt): Promise<DeepPartial<LPState>>;
  updatePartnerWhitelist(
    request: UpdatePartnerWhitelistRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<LPState>>;
  updateWallets(request: UpdateWalletsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<LPState>>;
  updateMaxPrincipal(
    request: UpdateMaxPrincipalRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<LPState>>;
  updateCliffPeriod(
    request: UpdateCliffPeriodRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<LPState>>;
  approveWithdraw(
    request: ApproveWithdrawRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<LPState>>;
  rejectWithdraw(request: RejectWithdrawRequest, context: CallContext & CallContextExt): Promise<DeepPartial<LPState>>;
}

export interface OrbitClient<CallOptionsExt = {}> {
  getVaultPda(request: DeepPartial<GetPdaRequest>, options?: CallOptions & CallOptionsExt): Promise<PdaResponse>;
  getOrderPda(request: DeepPartial<GetPdaRequest>, options?: CallOptions & CallOptionsExt): Promise<PdaResponse>;
  readOrderPda(request: DeepPartial<GetPdaRequest>, options?: CallOptions & CallOptionsExt): Promise<OrderData>;
  collect(request: DeepPartial<CollectRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
  disburse(request: DeepPartial<DisburseRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
  decodeEvent(request: DeepPartial<DecodeEventRequest>, options?: CallOptions & CallOptionsExt): Promise<EventData>;
  /** ── LP / user-management (admin-signed, published via Squads) ──────────── */
  verifyUser(request: DeepPartial<VerifyUserRequest>, options?: CallOptions & CallOptionsExt): Promise<LPState>;
  registerUser(request: DeepPartial<RegisterUserRequest>, options?: CallOptions & CallOptionsExt): Promise<LPState>;
  revokeLP(request: DeepPartial<RevokeRequest>, options?: CallOptions & CallOptionsExt): Promise<LPState>;
  updatePartnerWhitelist(
    request: DeepPartial<UpdatePartnerWhitelistRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<LPState>;
  updateWallets(request: DeepPartial<UpdateWalletsRequest>, options?: CallOptions & CallOptionsExt): Promise<LPState>;
  updateMaxPrincipal(
    request: DeepPartial<UpdateMaxPrincipalRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<LPState>;
  updateCliffPeriod(
    request: DeepPartial<UpdateCliffPeriodRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<LPState>;
  approveWithdraw(
    request: DeepPartial<ApproveWithdrawRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<LPState>;
  rejectWithdraw(request: DeepPartial<RejectWithdrawRequest>, options?: CallOptions & CallOptionsExt): Promise<LPState>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
