// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: orbit.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { DecodeEventRequest, Ed25519Pair, EventData, Token, tokenFromJSON, tokenToJSON } from "./base";

export const protobufPackage = "orbit";

export interface DomainSeparatorRequest {
}

export interface DomainSeparatorResponse {
  domainSeparator: number;
}

export interface GetPdaRequest {
  key?: string | undefined;
}

export interface PdaResponse {
  pda: string;
  key: string;
  type: string;
}

export interface SpendTokensRequest {
  requestId: string;
  approver: string;
  amount: string;
  delegateKey?: string | undefined;
  token?: Token | undefined;
}

export interface TransferToLpRequest {
  requestId: string;
  to: string;
  amount: string;
  token?: Token | undefined;
}

export interface TransferPdaToWalletRequest {
  requestId: string;
  userKey: string;
  to: string;
  amount: string;
  ed25519Pair?: Ed25519Pair | undefined;
  token?: Token | undefined;
}

export interface TxResponse {
  requestId: string;
  signature: string;
  position: number;
}

function createBaseDomainSeparatorRequest(): DomainSeparatorRequest {
  return {};
}

export const DomainSeparatorRequest: MessageFns<DomainSeparatorRequest> = {
  encode(_: DomainSeparatorRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DomainSeparatorRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDomainSeparatorRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DomainSeparatorRequest {
    return {};
  },

  toJSON(_: DomainSeparatorRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DomainSeparatorRequest>, I>>(base?: I): DomainSeparatorRequest {
    return DomainSeparatorRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DomainSeparatorRequest>, I>>(_: I): DomainSeparatorRequest {
    const message = createBaseDomainSeparatorRequest();
    return message;
  },
};

function createBaseDomainSeparatorResponse(): DomainSeparatorResponse {
  return { domainSeparator: 0 };
}

export const DomainSeparatorResponse: MessageFns<DomainSeparatorResponse> = {
  encode(message: DomainSeparatorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.domainSeparator !== 0) {
      writer.uint32(8).int64(message.domainSeparator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DomainSeparatorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDomainSeparatorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.domainSeparator = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DomainSeparatorResponse {
    return {
      domainSeparator: isSet(object.domainSeparator)
        ? globalThis.Number(object.domainSeparator)
        : isSet(object.domain_separator)
        ? globalThis.Number(object.domain_separator)
        : 0,
    };
  },

  toJSON(message: DomainSeparatorResponse): unknown {
    const obj: any = {};
    if (message.domainSeparator !== 0) {
      obj.domainSeparator = Math.round(message.domainSeparator);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DomainSeparatorResponse>, I>>(base?: I): DomainSeparatorResponse {
    return DomainSeparatorResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DomainSeparatorResponse>, I>>(object: I): DomainSeparatorResponse {
    const message = createBaseDomainSeparatorResponse();
    message.domainSeparator = object.domainSeparator ?? 0;
    return message;
  },
};

function createBaseGetPdaRequest(): GetPdaRequest {
  return { key: undefined };
}

export const GetPdaRequest: MessageFns<GetPdaRequest> = {
  encode(message: GetPdaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== undefined) {
      writer.uint32(10).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPdaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPdaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPdaRequest {
    return { key: isSet(object.key) ? globalThis.String(object.key) : undefined };
  },

  toJSON(message: GetPdaRequest): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPdaRequest>, I>>(base?: I): GetPdaRequest {
    return GetPdaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPdaRequest>, I>>(object: I): GetPdaRequest {
    const message = createBaseGetPdaRequest();
    message.key = object.key ?? undefined;
    return message;
  },
};

function createBasePdaResponse(): PdaResponse {
  return { pda: "", key: "", type: "" };
}

export const PdaResponse: MessageFns<PdaResponse> = {
  encode(message: PdaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pda !== "") {
      writer.uint32(10).string(message.pda);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PdaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePdaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pda = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PdaResponse {
    return {
      pda: isSet(object.pda) ? globalThis.String(object.pda) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
    };
  },

  toJSON(message: PdaResponse): unknown {
    const obj: any = {};
    if (message.pda !== "") {
      obj.pda = message.pda;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PdaResponse>, I>>(base?: I): PdaResponse {
    return PdaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PdaResponse>, I>>(object: I): PdaResponse {
    const message = createBasePdaResponse();
    message.pda = object.pda ?? "";
    message.key = object.key ?? "";
    message.type = object.type ?? "";
    return message;
  },
};

function createBaseSpendTokensRequest(): SpendTokensRequest {
  return { requestId: "", approver: "", amount: "", delegateKey: undefined, token: undefined };
}

export const SpendTokensRequest: MessageFns<SpendTokensRequest> = {
  encode(message: SpendTokensRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.approver !== "") {
      writer.uint32(18).string(message.approver);
    }
    if (message.amount !== "") {
      writer.uint32(26).string(message.amount);
    }
    if (message.delegateKey !== undefined) {
      writer.uint32(34).string(message.delegateKey);
    }
    if (message.token !== undefined) {
      writer.uint32(40).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpendTokensRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpendTokensRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.approver = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.delegateKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpendTokensRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      approver: isSet(object.approver) ? globalThis.String(object.approver) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      delegateKey: isSet(object.delegateKey)
        ? globalThis.String(object.delegateKey)
        : isSet(object.delegate_key)
        ? globalThis.String(object.delegate_key)
        : undefined,
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: SpendTokensRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.approver !== "") {
      obj.approver = message.approver;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.delegateKey !== undefined) {
      obj.delegateKey = message.delegateKey;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpendTokensRequest>, I>>(base?: I): SpendTokensRequest {
    return SpendTokensRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpendTokensRequest>, I>>(object: I): SpendTokensRequest {
    const message = createBaseSpendTokensRequest();
    message.requestId = object.requestId ?? "";
    message.approver = object.approver ?? "";
    message.amount = object.amount ?? "";
    message.delegateKey = object.delegateKey ?? undefined;
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseTransferToLpRequest(): TransferToLpRequest {
  return { requestId: "", to: "", amount: "", token: undefined };
}

export const TransferToLpRequest: MessageFns<TransferToLpRequest> = {
  encode(message: TransferToLpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.to !== "") {
      writer.uint32(18).string(message.to);
    }
    if (message.amount !== "") {
      writer.uint32(26).string(message.amount);
    }
    if (message.token !== undefined) {
      writer.uint32(32).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferToLpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransferToLpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransferToLpRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: TransferToLpRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransferToLpRequest>, I>>(base?: I): TransferToLpRequest {
    return TransferToLpRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransferToLpRequest>, I>>(object: I): TransferToLpRequest {
    const message = createBaseTransferToLpRequest();
    message.requestId = object.requestId ?? "";
    message.to = object.to ?? "";
    message.amount = object.amount ?? "";
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseTransferPdaToWalletRequest(): TransferPdaToWalletRequest {
  return { requestId: "", userKey: "", to: "", amount: "", ed25519Pair: undefined, token: undefined };
}

export const TransferPdaToWalletRequest: MessageFns<TransferPdaToWalletRequest> = {
  encode(message: TransferPdaToWalletRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.userKey !== "") {
      writer.uint32(18).string(message.userKey);
    }
    if (message.to !== "") {
      writer.uint32(26).string(message.to);
    }
    if (message.amount !== "") {
      writer.uint32(34).string(message.amount);
    }
    if (message.ed25519Pair !== undefined) {
      Ed25519Pair.encode(message.ed25519Pair, writer.uint32(42).fork()).join();
    }
    if (message.token !== undefined) {
      writer.uint32(48).int32(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferPdaToWalletRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransferPdaToWalletRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ed25519Pair = Ed25519Pair.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransferPdaToWalletRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      userKey: isSet(object.userKey)
        ? globalThis.String(object.userKey)
        : isSet(object.user_key)
        ? globalThis.String(object.user_key)
        : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      ed25519Pair: isSet(object.ed25519Pair)
        ? Ed25519Pair.fromJSON(object.ed25519Pair)
        : isSet(object.ed25519_pair)
        ? Ed25519Pair.fromJSON(object.ed25519_pair)
        : undefined,
      token: isSet(object.token) ? tokenFromJSON(object.token) : undefined,
    };
  },

  toJSON(message: TransferPdaToWalletRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.userKey !== "") {
      obj.userKey = message.userKey;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.ed25519Pair !== undefined) {
      obj.ed25519Pair = Ed25519Pair.toJSON(message.ed25519Pair);
    }
    if (message.token !== undefined) {
      obj.token = tokenToJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransferPdaToWalletRequest>, I>>(base?: I): TransferPdaToWalletRequest {
    return TransferPdaToWalletRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransferPdaToWalletRequest>, I>>(object: I): TransferPdaToWalletRequest {
    const message = createBaseTransferPdaToWalletRequest();
    message.requestId = object.requestId ?? "";
    message.userKey = object.userKey ?? "";
    message.to = object.to ?? "";
    message.amount = object.amount ?? "";
    message.ed25519Pair = (object.ed25519Pair !== undefined && object.ed25519Pair !== null)
      ? Ed25519Pair.fromPartial(object.ed25519Pair)
      : undefined;
    message.token = object.token ?? undefined;
    return message;
  },
};

function createBaseTxResponse(): TxResponse {
  return { requestId: "", signature: "", position: 0 };
}

export const TxResponse: MessageFns<TxResponse> = {
  encode(message: TxResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.signature !== "") {
      writer.uint32(18).string(message.signature);
    }
    if (message.position !== 0) {
      writer.uint32(24).int64(message.position);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.position = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxResponse {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
    };
  },

  toJSON(message: TxResponse): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxResponse>, I>>(base?: I): TxResponse {
    return TxResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxResponse>, I>>(object: I): TxResponse {
    const message = createBaseTxResponse();
    message.requestId = object.requestId ?? "";
    message.signature = object.signature ?? "";
    message.position = object.position ?? 0;
    return message;
  },
};

export type OrbitDefinition = typeof OrbitDefinition;
export const OrbitDefinition = {
  name: "Orbit",
  fullName: "orbit.Orbit",
  methods: {
    domainSeparator: {
      name: "DomainSeparator",
      requestType: DomainSeparatorRequest as typeof DomainSeparatorRequest,
      requestStream: false,
      responseType: DomainSeparatorResponse as typeof DomainSeparatorResponse,
      responseStream: false,
      options: {},
    },
    getUserPda: {
      name: "GetUserPda",
      requestType: GetPdaRequest as typeof GetPdaRequest,
      requestStream: false,
      responseType: PdaResponse as typeof PdaResponse,
      responseStream: false,
      options: {},
    },
    getDelegatePda: {
      name: "GetDelegatePda",
      requestType: GetPdaRequest as typeof GetPdaRequest,
      requestStream: false,
      responseType: PdaResponse as typeof PdaResponse,
      responseStream: false,
      options: {},
    },
    spendTokens: {
      name: "SpendTokens",
      requestType: SpendTokensRequest as typeof SpendTokensRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    transferToLp: {
      name: "TransferToLp",
      requestType: TransferToLpRequest as typeof TransferToLpRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    transferPdaToWallet: {
      name: "TransferPdaToWallet",
      requestType: TransferPdaToWalletRequest as typeof TransferPdaToWalletRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    decodeEvent: {
      name: "DecodeEvent",
      requestType: DecodeEventRequest as typeof DecodeEventRequest,
      requestStream: false,
      responseType: EventData as typeof EventData,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface OrbitServiceImplementation<CallContextExt = {}> {
  domainSeparator(
    request: DomainSeparatorRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<DomainSeparatorResponse>>;
  getUserPda(request: GetPdaRequest, context: CallContext & CallContextExt): Promise<DeepPartial<PdaResponse>>;
  getDelegatePda(request: GetPdaRequest, context: CallContext & CallContextExt): Promise<DeepPartial<PdaResponse>>;
  spendTokens(request: SpendTokensRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
  transferToLp(request: TransferToLpRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
  transferPdaToWallet(
    request: TransferPdaToWalletRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<TxResponse>>;
  decodeEvent(request: DecodeEventRequest, context: CallContext & CallContextExt): Promise<DeepPartial<EventData>>;
}

export interface OrbitClient<CallOptionsExt = {}> {
  domainSeparator(
    request: DeepPartial<DomainSeparatorRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<DomainSeparatorResponse>;
  getUserPda(request: DeepPartial<GetPdaRequest>, options?: CallOptions & CallOptionsExt): Promise<PdaResponse>;
  getDelegatePda(request: DeepPartial<GetPdaRequest>, options?: CallOptions & CallOptionsExt): Promise<PdaResponse>;
  spendTokens(request: DeepPartial<SpendTokensRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
  transferToLp(request: DeepPartial<TransferToLpRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
  transferPdaToWallet(
    request: DeepPartial<TransferPdaToWalletRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<TxResponse>;
  decodeEvent(request: DeepPartial<DecodeEventRequest>, options?: CallOptions & CallOptionsExt): Promise<EventData>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
