// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.36.2
// source: tr.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "tr";

export interface CreatePoolRequest {
  poolId: string;
  partnerId: string;
  /** BATCH or REALTIME. */
  model: string;
}

export interface ReadPoolRequest {
  poolId: string;
}

/**
 * `pool_id` and `partner_id` are the ids the account stores: the first 32 hex
 * characters of the SHA-256 of the backend's ids.
 */
export interface PoolData {
  address: string;
  poolId: string;
  partnerId: string;
  model: string;
  lastSequence: number;
  batchCount: number;
  createdAt: number;
  /** The creating transaction, when this call made it. */
  signature?: string | undefined;
}

export interface ReadPoolResponse {
  pool?: PoolData | undefined;
}

export interface AnchorBatchRequest {
  /** The pool's address. */
  pool: string;
  batchId: string;
  /** 64 hex characters. */
  merkleRoot: string;
  sequenceFrom: number;
  sequenceTo: number;
}

export interface ReadBatchRequest {
  /** The pool's address. */
  pool: string;
  sequenceFrom: number;
}

/**
 * `batch_id` is the id the account stores: the first 32 hex characters of the
 * SHA-256 of the backend's id.
 */
export interface BatchData {
  address: string;
  pool: string;
  batchId: string;
  merkleRoot: string;
  sequenceFrom: number;
  sequenceTo: number;
  anchoredAt: number;
  /** The anchoring transaction. */
  signature?: string | undefined;
}

export interface ReadBatchResponse {
  batch?: BatchData | undefined;
}

function createBaseCreatePoolRequest(): CreatePoolRequest {
  return { poolId: "", partnerId: "", model: "" };
}

export const CreatePoolRequest: MessageFns<CreatePoolRequest> = {
  encode(message: CreatePoolRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.poolId !== "") {
      writer.uint32(10).string(message.poolId);
    }
    if (message.partnerId !== "") {
      writer.uint32(18).string(message.partnerId);
    }
    if (message.model !== "") {
      writer.uint32(26).string(message.model);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreatePoolRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatePoolRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.poolId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.partnerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.model = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreatePoolRequest {
    return {
      poolId: isSet(object.poolId)
        ? globalThis.String(object.poolId)
        : isSet(object.pool_id)
        ? globalThis.String(object.pool_id)
        : "",
      partnerId: isSet(object.partnerId)
        ? globalThis.String(object.partnerId)
        : isSet(object.partner_id)
        ? globalThis.String(object.partner_id)
        : "",
      model: isSet(object.model) ? globalThis.String(object.model) : "",
    };
  },

  toJSON(message: CreatePoolRequest): unknown {
    const obj: any = {};
    if (message.poolId !== "") {
      obj.poolId = message.poolId;
    }
    if (message.partnerId !== "") {
      obj.partnerId = message.partnerId;
    }
    if (message.model !== "") {
      obj.model = message.model;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreatePoolRequest>, I>>(base?: I): CreatePoolRequest {
    return CreatePoolRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreatePoolRequest>, I>>(object: I): CreatePoolRequest {
    const message = createBaseCreatePoolRequest();
    message.poolId = object.poolId ?? "";
    message.partnerId = object.partnerId ?? "";
    message.model = object.model ?? "";
    return message;
  },
};

function createBaseReadPoolRequest(): ReadPoolRequest {
  return { poolId: "" };
}

export const ReadPoolRequest: MessageFns<ReadPoolRequest> = {
  encode(message: ReadPoolRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.poolId !== "") {
      writer.uint32(10).string(message.poolId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadPoolRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadPoolRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.poolId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadPoolRequest {
    return {
      poolId: isSet(object.poolId)
        ? globalThis.String(object.poolId)
        : isSet(object.pool_id)
        ? globalThis.String(object.pool_id)
        : "",
    };
  },

  toJSON(message: ReadPoolRequest): unknown {
    const obj: any = {};
    if (message.poolId !== "") {
      obj.poolId = message.poolId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadPoolRequest>, I>>(base?: I): ReadPoolRequest {
    return ReadPoolRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadPoolRequest>, I>>(object: I): ReadPoolRequest {
    const message = createBaseReadPoolRequest();
    message.poolId = object.poolId ?? "";
    return message;
  },
};

function createBasePoolData(): PoolData {
  return {
    address: "",
    poolId: "",
    partnerId: "",
    model: "",
    lastSequence: 0,
    batchCount: 0,
    createdAt: 0,
    signature: undefined,
  };
}

export const PoolData: MessageFns<PoolData> = {
  encode(message: PoolData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.poolId !== "") {
      writer.uint32(18).string(message.poolId);
    }
    if (message.partnerId !== "") {
      writer.uint32(26).string(message.partnerId);
    }
    if (message.model !== "") {
      writer.uint32(34).string(message.model);
    }
    if (message.lastSequence !== 0) {
      writer.uint32(40).uint64(message.lastSequence);
    }
    if (message.batchCount !== 0) {
      writer.uint32(48).uint64(message.batchCount);
    }
    if (message.createdAt !== 0) {
      writer.uint32(56).int64(message.createdAt);
    }
    if (message.signature !== undefined) {
      writer.uint32(66).string(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PoolData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePoolData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.poolId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.partnerId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.model = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lastSequence = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.batchCount = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PoolData {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      poolId: isSet(object.poolId)
        ? globalThis.String(object.poolId)
        : isSet(object.pool_id)
        ? globalThis.String(object.pool_id)
        : "",
      partnerId: isSet(object.partnerId)
        ? globalThis.String(object.partnerId)
        : isSet(object.partner_id)
        ? globalThis.String(object.partner_id)
        : "",
      model: isSet(object.model) ? globalThis.String(object.model) : "",
      lastSequence: isSet(object.lastSequence)
        ? globalThis.Number(object.lastSequence)
        : isSet(object.last_sequence)
        ? globalThis.Number(object.last_sequence)
        : 0,
      batchCount: isSet(object.batchCount)
        ? globalThis.Number(object.batchCount)
        : isSet(object.batch_count)
        ? globalThis.Number(object.batch_count)
        : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      signature: isSet(object.signature) ? globalThis.String(object.signature) : undefined,
    };
  },

  toJSON(message: PoolData): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.poolId !== "") {
      obj.poolId = message.poolId;
    }
    if (message.partnerId !== "") {
      obj.partnerId = message.partnerId;
    }
    if (message.model !== "") {
      obj.model = message.model;
    }
    if (message.lastSequence !== 0) {
      obj.lastSequence = Math.round(message.lastSequence);
    }
    if (message.batchCount !== 0) {
      obj.batchCount = Math.round(message.batchCount);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.signature !== undefined) {
      obj.signature = message.signature;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PoolData>, I>>(base?: I): PoolData {
    return PoolData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PoolData>, I>>(object: I): PoolData {
    const message = createBasePoolData();
    message.address = object.address ?? "";
    message.poolId = object.poolId ?? "";
    message.partnerId = object.partnerId ?? "";
    message.model = object.model ?? "";
    message.lastSequence = object.lastSequence ?? 0;
    message.batchCount = object.batchCount ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.signature = object.signature ?? undefined;
    return message;
  },
};

function createBaseReadPoolResponse(): ReadPoolResponse {
  return { pool: undefined };
}

export const ReadPoolResponse: MessageFns<ReadPoolResponse> = {
  encode(message: ReadPoolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pool !== undefined) {
      PoolData.encode(message.pool, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadPoolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadPoolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pool = PoolData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadPoolResponse {
    return { pool: isSet(object.pool) ? PoolData.fromJSON(object.pool) : undefined };
  },

  toJSON(message: ReadPoolResponse): unknown {
    const obj: any = {};
    if (message.pool !== undefined) {
      obj.pool = PoolData.toJSON(message.pool);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadPoolResponse>, I>>(base?: I): ReadPoolResponse {
    return ReadPoolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadPoolResponse>, I>>(object: I): ReadPoolResponse {
    const message = createBaseReadPoolResponse();
    message.pool = (object.pool !== undefined && object.pool !== null) ? PoolData.fromPartial(object.pool) : undefined;
    return message;
  },
};

function createBaseAnchorBatchRequest(): AnchorBatchRequest {
  return { pool: "", batchId: "", merkleRoot: "", sequenceFrom: 0, sequenceTo: 0 };
}

export const AnchorBatchRequest: MessageFns<AnchorBatchRequest> = {
  encode(message: AnchorBatchRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pool !== "") {
      writer.uint32(10).string(message.pool);
    }
    if (message.batchId !== "") {
      writer.uint32(18).string(message.batchId);
    }
    if (message.merkleRoot !== "") {
      writer.uint32(26).string(message.merkleRoot);
    }
    if (message.sequenceFrom !== 0) {
      writer.uint32(32).uint64(message.sequenceFrom);
    }
    if (message.sequenceTo !== 0) {
      writer.uint32(40).uint64(message.sequenceTo);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnchorBatchRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnchorBatchRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pool = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.batchId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.merkleRoot = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.sequenceFrom = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.sequenceTo = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnchorBatchRequest {
    return {
      pool: isSet(object.pool) ? globalThis.String(object.pool) : "",
      batchId: isSet(object.batchId)
        ? globalThis.String(object.batchId)
        : isSet(object.batch_id)
        ? globalThis.String(object.batch_id)
        : "",
      merkleRoot: isSet(object.merkleRoot)
        ? globalThis.String(object.merkleRoot)
        : isSet(object.merkle_root)
        ? globalThis.String(object.merkle_root)
        : "",
      sequenceFrom: isSet(object.sequenceFrom)
        ? globalThis.Number(object.sequenceFrom)
        : isSet(object.sequence_from)
        ? globalThis.Number(object.sequence_from)
        : 0,
      sequenceTo: isSet(object.sequenceTo)
        ? globalThis.Number(object.sequenceTo)
        : isSet(object.sequence_to)
        ? globalThis.Number(object.sequence_to)
        : 0,
    };
  },

  toJSON(message: AnchorBatchRequest): unknown {
    const obj: any = {};
    if (message.pool !== "") {
      obj.pool = message.pool;
    }
    if (message.batchId !== "") {
      obj.batchId = message.batchId;
    }
    if (message.merkleRoot !== "") {
      obj.merkleRoot = message.merkleRoot;
    }
    if (message.sequenceFrom !== 0) {
      obj.sequenceFrom = Math.round(message.sequenceFrom);
    }
    if (message.sequenceTo !== 0) {
      obj.sequenceTo = Math.round(message.sequenceTo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AnchorBatchRequest>, I>>(base?: I): AnchorBatchRequest {
    return AnchorBatchRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AnchorBatchRequest>, I>>(object: I): AnchorBatchRequest {
    const message = createBaseAnchorBatchRequest();
    message.pool = object.pool ?? "";
    message.batchId = object.batchId ?? "";
    message.merkleRoot = object.merkleRoot ?? "";
    message.sequenceFrom = object.sequenceFrom ?? 0;
    message.sequenceTo = object.sequenceTo ?? 0;
    return message;
  },
};

function createBaseReadBatchRequest(): ReadBatchRequest {
  return { pool: "", sequenceFrom: 0 };
}

export const ReadBatchRequest: MessageFns<ReadBatchRequest> = {
  encode(message: ReadBatchRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pool !== "") {
      writer.uint32(10).string(message.pool);
    }
    if (message.sequenceFrom !== 0) {
      writer.uint32(16).uint64(message.sequenceFrom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadBatchRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadBatchRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pool = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sequenceFrom = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadBatchRequest {
    return {
      pool: isSet(object.pool) ? globalThis.String(object.pool) : "",
      sequenceFrom: isSet(object.sequenceFrom)
        ? globalThis.Number(object.sequenceFrom)
        : isSet(object.sequence_from)
        ? globalThis.Number(object.sequence_from)
        : 0,
    };
  },

  toJSON(message: ReadBatchRequest): unknown {
    const obj: any = {};
    if (message.pool !== "") {
      obj.pool = message.pool;
    }
    if (message.sequenceFrom !== 0) {
      obj.sequenceFrom = Math.round(message.sequenceFrom);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadBatchRequest>, I>>(base?: I): ReadBatchRequest {
    return ReadBatchRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadBatchRequest>, I>>(object: I): ReadBatchRequest {
    const message = createBaseReadBatchRequest();
    message.pool = object.pool ?? "";
    message.sequenceFrom = object.sequenceFrom ?? 0;
    return message;
  },
};

function createBaseBatchData(): BatchData {
  return {
    address: "",
    pool: "",
    batchId: "",
    merkleRoot: "",
    sequenceFrom: 0,
    sequenceTo: 0,
    anchoredAt: 0,
    signature: undefined,
  };
}

export const BatchData: MessageFns<BatchData> = {
  encode(message: BatchData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.pool !== "") {
      writer.uint32(18).string(message.pool);
    }
    if (message.batchId !== "") {
      writer.uint32(26).string(message.batchId);
    }
    if (message.merkleRoot !== "") {
      writer.uint32(34).string(message.merkleRoot);
    }
    if (message.sequenceFrom !== 0) {
      writer.uint32(40).uint64(message.sequenceFrom);
    }
    if (message.sequenceTo !== 0) {
      writer.uint32(48).uint64(message.sequenceTo);
    }
    if (message.anchoredAt !== 0) {
      writer.uint32(56).int64(message.anchoredAt);
    }
    if (message.signature !== undefined) {
      writer.uint32(66).string(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BatchData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBatchData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pool = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.batchId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.merkleRoot = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.sequenceFrom = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sequenceTo = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.anchoredAt = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BatchData {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      pool: isSet(object.pool) ? globalThis.String(object.pool) : "",
      batchId: isSet(object.batchId)
        ? globalThis.String(object.batchId)
        : isSet(object.batch_id)
        ? globalThis.String(object.batch_id)
        : "",
      merkleRoot: isSet(object.merkleRoot)
        ? globalThis.String(object.merkleRoot)
        : isSet(object.merkle_root)
        ? globalThis.String(object.merkle_root)
        : "",
      sequenceFrom: isSet(object.sequenceFrom)
        ? globalThis.Number(object.sequenceFrom)
        : isSet(object.sequence_from)
        ? globalThis.Number(object.sequence_from)
        : 0,
      sequenceTo: isSet(object.sequenceTo)
        ? globalThis.Number(object.sequenceTo)
        : isSet(object.sequence_to)
        ? globalThis.Number(object.sequence_to)
        : 0,
      anchoredAt: isSet(object.anchoredAt)
        ? globalThis.Number(object.anchoredAt)
        : isSet(object.anchored_at)
        ? globalThis.Number(object.anchored_at)
        : 0,
      signature: isSet(object.signature) ? globalThis.String(object.signature) : undefined,
    };
  },

  toJSON(message: BatchData): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.pool !== "") {
      obj.pool = message.pool;
    }
    if (message.batchId !== "") {
      obj.batchId = message.batchId;
    }
    if (message.merkleRoot !== "") {
      obj.merkleRoot = message.merkleRoot;
    }
    if (message.sequenceFrom !== 0) {
      obj.sequenceFrom = Math.round(message.sequenceFrom);
    }
    if (message.sequenceTo !== 0) {
      obj.sequenceTo = Math.round(message.sequenceTo);
    }
    if (message.anchoredAt !== 0) {
      obj.anchoredAt = Math.round(message.anchoredAt);
    }
    if (message.signature !== undefined) {
      obj.signature = message.signature;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BatchData>, I>>(base?: I): BatchData {
    return BatchData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BatchData>, I>>(object: I): BatchData {
    const message = createBaseBatchData();
    message.address = object.address ?? "";
    message.pool = object.pool ?? "";
    message.batchId = object.batchId ?? "";
    message.merkleRoot = object.merkleRoot ?? "";
    message.sequenceFrom = object.sequenceFrom ?? 0;
    message.sequenceTo = object.sequenceTo ?? 0;
    message.anchoredAt = object.anchoredAt ?? 0;
    message.signature = object.signature ?? undefined;
    return message;
  },
};

function createBaseReadBatchResponse(): ReadBatchResponse {
  return { batch: undefined };
}

export const ReadBatchResponse: MessageFns<ReadBatchResponse> = {
  encode(message: ReadBatchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.batch !== undefined) {
      BatchData.encode(message.batch, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReadBatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReadBatchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.batch = BatchData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReadBatchResponse {
    return { batch: isSet(object.batch) ? BatchData.fromJSON(object.batch) : undefined };
  },

  toJSON(message: ReadBatchResponse): unknown {
    const obj: any = {};
    if (message.batch !== undefined) {
      obj.batch = BatchData.toJSON(message.batch);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReadBatchResponse>, I>>(base?: I): ReadBatchResponse {
    return ReadBatchResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReadBatchResponse>, I>>(object: I): ReadBatchResponse {
    const message = createBaseReadBatchResponse();
    message.batch = (object.batch !== undefined && object.batch !== null)
      ? BatchData.fromPartial(object.batch)
      : undefined;
    return message;
  },
};

export type TrDefinition = typeof TrDefinition;
export const TrDefinition = {
  name: "Tr",
  fullName: "tr.Tr",
  methods: {
    createPool: {
      name: "CreatePool",
      requestType: CreatePoolRequest as typeof CreatePoolRequest,
      requestStream: false,
      responseType: PoolData as typeof PoolData,
      responseStream: false,
      options: {},
    },
    readPool: {
      name: "ReadPool",
      requestType: ReadPoolRequest as typeof ReadPoolRequest,
      requestStream: false,
      responseType: ReadPoolResponse as typeof ReadPoolResponse,
      responseStream: false,
      options: {},
    },
    anchorBatch: {
      name: "AnchorBatch",
      requestType: AnchorBatchRequest as typeof AnchorBatchRequest,
      requestStream: false,
      responseType: BatchData as typeof BatchData,
      responseStream: false,
      options: {},
    },
    readBatch: {
      name: "ReadBatch",
      requestType: ReadBatchRequest as typeof ReadBatchRequest,
      requestStream: false,
      responseType: ReadBatchResponse as typeof ReadBatchResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface TrServiceImplementation<CallContextExt = {}> {
  createPool(request: CreatePoolRequest, context: CallContext & CallContextExt): Promise<DeepPartial<PoolData>>;
  readPool(request: ReadPoolRequest, context: CallContext & CallContextExt): Promise<DeepPartial<ReadPoolResponse>>;
  anchorBatch(request: AnchorBatchRequest, context: CallContext & CallContextExt): Promise<DeepPartial<BatchData>>;
  readBatch(request: ReadBatchRequest, context: CallContext & CallContextExt): Promise<DeepPartial<ReadBatchResponse>>;
}

export interface TrClient<CallOptionsExt = {}> {
  createPool(request: DeepPartial<CreatePoolRequest>, options?: CallOptions & CallOptionsExt): Promise<PoolData>;
  readPool(request: DeepPartial<ReadPoolRequest>, options?: CallOptions & CallOptionsExt): Promise<ReadPoolResponse>;
  anchorBatch(request: DeepPartial<AnchorBatchRequest>, options?: CallOptions & CallOptionsExt): Promise<BatchData>;
  readBatch(request: DeepPartial<ReadBatchRequest>, options?: CallOptions & CallOptionsExt): Promise<ReadBatchResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
