// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: base.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "base";

export enum Token {
  USDC = 0,
  USDT = 1,
  PYUSD = 2,
  USD1 = 3,
  RLUSD = 4,
  UNRECOGNIZED = -1,
}

export function tokenFromJSON(object: any): Token {
  switch (object) {
    case 0:
    case "USDC":
      return Token.USDC;
    case 1:
    case "USDT":
      return Token.USDT;
    case 2:
    case "PYUSD":
      return Token.PYUSD;
    case 3:
    case "USD1":
      return Token.USD1;
    case 4:
    case "RLUSD":
      return Token.RLUSD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Token.UNRECOGNIZED;
  }
}

export function tokenToJSON(object: Token): string {
  switch (object) {
    case Token.USDC:
      return "USDC";
    case Token.USDT:
      return "USDT";
    case Token.PYUSD:
      return "PYUSD";
    case Token.USD1:
      return "USD1";
    case Token.RLUSD:
      return "RLUSD";
    case Token.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Denom {
  LAMPORTS = 0,
  SOL = 1,
  UNRECOGNIZED = -1,
}

export function denomFromJSON(object: any): Denom {
  switch (object) {
    case 0:
    case "LAMPORTS":
      return Denom.LAMPORTS;
    case 1:
    case "SOL":
      return Denom.SOL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Denom.UNRECOGNIZED;
  }
}

export function denomToJSON(object: Denom): string {
  switch (object) {
    case Denom.LAMPORTS:
      return "LAMPORTS";
    case Denom.SOL:
      return "SOL";
    case Denom.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface TxIxAccount {
  pubkey: string;
  isSigner: boolean;
  isWritable: boolean;
}

export interface TxIx {
  programId: string;
  data: Buffer;
  keys: TxIxAccount[];
}

export interface GenerateHashedArrayRequest {
  input: string;
}

export interface GenerateHashedArrayResponse {
  hashed: Buffer;
}

export interface BuildEd25519IxRequest {
  message: string;
  signer: string;
}

export interface Ed25519Pair {
  ed25519Sig: Buffer;
  ed25519Ix?: TxIx | undefined;
}

export interface GetAccountInfoRequest {
  address: string;
}

export interface GetAccountInfoResponse {
  owner?: string | undefined;
  lamports?: number | undefined;
  data?: Buffer | undefined;
  executable?: boolean | undefined;
}

export interface GetOwnerRequest {
  address: string;
}

export interface GetOwnerResponse {
  owner: string;
}

export interface GetTokenAccountOwnerRequest {
  address: string;
}

export interface GetTokenAccountOwnerResponse {
  owner: string;
}

export interface GetAtaAddressRequest {
  token: Token;
  owner: string;
}

export interface GetAtaAddressResponse {
  ata: string;
}

export interface GetOrCreateAtaRequest {
  token: Token;
  owner: string;
  maxAttempts?: number | undefined;
}

export interface GetOrCreateAtaResponse {
  ata: string;
  tokenAccount?: GetAccountInfoResponse | undefined;
  txId?: string | undefined;
}

export interface ExecuteTxRequest {
  requestId: string;
  ixs: TxIx[];
  signers: string[];
}

export interface ExecuteTxResponse {
  requestId: string;
  txId: string;
}

export interface GetTxStatusRequest {
  txId: string;
  confirmation?: string | undefined;
}

export interface TxStatus {
  status: string;
  slot: number;
}

export interface GetTxDetailsRequest {
  txId: string;
  commitment?: string | undefined;
}

export interface TxDetails {
  stringified: string;
}

export interface GetTxCostRequest {
  txId: string;
  denom?: Denom | undefined;
}

export interface TxCost {
  txCost: number;
  denom: string;
}

function createBaseTxIxAccount(): TxIxAccount {
  return { pubkey: "", isSigner: false, isWritable: false };
}

export const TxIxAccount: MessageFns<TxIxAccount> = {
  encode(message: TxIxAccount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pubkey !== "") {
      writer.uint32(10).string(message.pubkey);
    }
    if (message.isSigner !== false) {
      writer.uint32(16).bool(message.isSigner);
    }
    if (message.isWritable !== false) {
      writer.uint32(24).bool(message.isWritable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxIxAccount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxIxAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pubkey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isSigner = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isWritable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxIxAccount {
    return {
      pubkey: isSet(object.pubkey) ? globalThis.String(object.pubkey) : "",
      isSigner: isSet(object.isSigner)
        ? globalThis.Boolean(object.isSigner)
        : isSet(object.is_signer)
        ? globalThis.Boolean(object.is_signer)
        : false,
      isWritable: isSet(object.isWritable)
        ? globalThis.Boolean(object.isWritable)
        : isSet(object.is_writable)
        ? globalThis.Boolean(object.is_writable)
        : false,
    };
  },

  toJSON(message: TxIxAccount): unknown {
    const obj: any = {};
    if (message.pubkey !== "") {
      obj.pubkey = message.pubkey;
    }
    if (message.isSigner !== false) {
      obj.isSigner = message.isSigner;
    }
    if (message.isWritable !== false) {
      obj.isWritable = message.isWritable;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxIxAccount>, I>>(base?: I): TxIxAccount {
    return TxIxAccount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxIxAccount>, I>>(object: I): TxIxAccount {
    const message = createBaseTxIxAccount();
    message.pubkey = object.pubkey ?? "";
    message.isSigner = object.isSigner ?? false;
    message.isWritable = object.isWritable ?? false;
    return message;
  },
};

function createBaseTxIx(): TxIx {
  return { programId: "", data: Buffer.alloc(0), keys: [] };
}

export const TxIx: MessageFns<TxIx> = {
  encode(message: TxIx, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.programId !== "") {
      writer.uint32(10).string(message.programId);
    }
    if (message.data.length !== 0) {
      writer.uint32(18).bytes(message.data);
    }
    for (const v of message.keys) {
      TxIxAccount.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxIx {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxIx();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.programId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.keys.push(TxIxAccount.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxIx {
    return {
      programId: isSet(object.programId)
        ? globalThis.String(object.programId)
        : isSet(object.program_id)
        ? globalThis.String(object.program_id)
        : "",
      data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : Buffer.alloc(0),
      keys: globalThis.Array.isArray(object?.keys) ? object.keys.map((e: any) => TxIxAccount.fromJSON(e)) : [],
    };
  },

  toJSON(message: TxIx): unknown {
    const obj: any = {};
    if (message.programId !== "") {
      obj.programId = message.programId;
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.keys?.length) {
      obj.keys = message.keys.map((e) => TxIxAccount.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxIx>, I>>(base?: I): TxIx {
    return TxIx.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxIx>, I>>(object: I): TxIx {
    const message = createBaseTxIx();
    message.programId = object.programId ?? "";
    message.data = object.data ?? Buffer.alloc(0);
    message.keys = object.keys?.map((e) => TxIxAccount.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGenerateHashedArrayRequest(): GenerateHashedArrayRequest {
  return { input: "" };
}

export const GenerateHashedArrayRequest: MessageFns<GenerateHashedArrayRequest> = {
  encode(message: GenerateHashedArrayRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.input !== "") {
      writer.uint32(10).string(message.input);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateHashedArrayRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateHashedArrayRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.input = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateHashedArrayRequest {
    return { input: isSet(object.input) ? globalThis.String(object.input) : "" };
  },

  toJSON(message: GenerateHashedArrayRequest): unknown {
    const obj: any = {};
    if (message.input !== "") {
      obj.input = message.input;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateHashedArrayRequest>, I>>(base?: I): GenerateHashedArrayRequest {
    return GenerateHashedArrayRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateHashedArrayRequest>, I>>(object: I): GenerateHashedArrayRequest {
    const message = createBaseGenerateHashedArrayRequest();
    message.input = object.input ?? "";
    return message;
  },
};

function createBaseGenerateHashedArrayResponse(): GenerateHashedArrayResponse {
  return { hashed: Buffer.alloc(0) };
}

export const GenerateHashedArrayResponse: MessageFns<GenerateHashedArrayResponse> = {
  encode(message: GenerateHashedArrayResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hashed.length !== 0) {
      writer.uint32(10).bytes(message.hashed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateHashedArrayResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateHashedArrayResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hashed = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateHashedArrayResponse {
    return { hashed: isSet(object.hashed) ? Buffer.from(bytesFromBase64(object.hashed)) : Buffer.alloc(0) };
  },

  toJSON(message: GenerateHashedArrayResponse): unknown {
    const obj: any = {};
    if (message.hashed.length !== 0) {
      obj.hashed = base64FromBytes(message.hashed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateHashedArrayResponse>, I>>(base?: I): GenerateHashedArrayResponse {
    return GenerateHashedArrayResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateHashedArrayResponse>, I>>(object: I): GenerateHashedArrayResponse {
    const message = createBaseGenerateHashedArrayResponse();
    message.hashed = object.hashed ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseBuildEd25519IxRequest(): BuildEd25519IxRequest {
  return { message: "", signer: "" };
}

export const BuildEd25519IxRequest: MessageFns<BuildEd25519IxRequest> = {
  encode(message: BuildEd25519IxRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.signer !== "") {
      writer.uint32(18).string(message.signer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BuildEd25519IxRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBuildEd25519IxRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BuildEd25519IxRequest {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
    };
  },

  toJSON(message: BuildEd25519IxRequest): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BuildEd25519IxRequest>, I>>(base?: I): BuildEd25519IxRequest {
    return BuildEd25519IxRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BuildEd25519IxRequest>, I>>(object: I): BuildEd25519IxRequest {
    const message = createBaseBuildEd25519IxRequest();
    message.message = object.message ?? "";
    message.signer = object.signer ?? "";
    return message;
  },
};

function createBaseEd25519Pair(): Ed25519Pair {
  return { ed25519Sig: Buffer.alloc(0), ed25519Ix: undefined };
}

export const Ed25519Pair: MessageFns<Ed25519Pair> = {
  encode(message: Ed25519Pair, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ed25519Sig.length !== 0) {
      writer.uint32(10).bytes(message.ed25519Sig);
    }
    if (message.ed25519Ix !== undefined) {
      TxIx.encode(message.ed25519Ix, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ed25519Pair {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEd25519Pair();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ed25519Sig = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ed25519Ix = TxIx.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Ed25519Pair {
    return {
      ed25519Sig: isSet(object.ed25519Sig)
        ? Buffer.from(bytesFromBase64(object.ed25519Sig))
        : isSet(object.ed25519_sig)
        ? Buffer.from(bytesFromBase64(object.ed25519_sig))
        : Buffer.alloc(0),
      ed25519Ix: isSet(object.ed25519Ix)
        ? TxIx.fromJSON(object.ed25519Ix)
        : isSet(object.ed25519_ix)
        ? TxIx.fromJSON(object.ed25519_ix)
        : undefined,
    };
  },

  toJSON(message: Ed25519Pair): unknown {
    const obj: any = {};
    if (message.ed25519Sig.length !== 0) {
      obj.ed25519Sig = base64FromBytes(message.ed25519Sig);
    }
    if (message.ed25519Ix !== undefined) {
      obj.ed25519Ix = TxIx.toJSON(message.ed25519Ix);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ed25519Pair>, I>>(base?: I): Ed25519Pair {
    return Ed25519Pair.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ed25519Pair>, I>>(object: I): Ed25519Pair {
    const message = createBaseEd25519Pair();
    message.ed25519Sig = object.ed25519Sig ?? Buffer.alloc(0);
    message.ed25519Ix = (object.ed25519Ix !== undefined && object.ed25519Ix !== null)
      ? TxIx.fromPartial(object.ed25519Ix)
      : undefined;
    return message;
  },
};

function createBaseGetAccountInfoRequest(): GetAccountInfoRequest {
  return { address: "" };
}

export const GetAccountInfoRequest: MessageFns<GetAccountInfoRequest> = {
  encode(message: GetAccountInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccountInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccountInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccountInfoRequest {
    return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
  },

  toJSON(message: GetAccountInfoRequest): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccountInfoRequest>, I>>(base?: I): GetAccountInfoRequest {
    return GetAccountInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccountInfoRequest>, I>>(object: I): GetAccountInfoRequest {
    const message = createBaseGetAccountInfoRequest();
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseGetAccountInfoResponse(): GetAccountInfoResponse {
  return { owner: undefined, lamports: undefined, data: undefined, executable: undefined };
}

export const GetAccountInfoResponse: MessageFns<GetAccountInfoResponse> = {
  encode(message: GetAccountInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.owner !== undefined) {
      writer.uint32(10).string(message.owner);
    }
    if (message.lamports !== undefined) {
      writer.uint32(16).uint64(message.lamports);
    }
    if (message.data !== undefined) {
      writer.uint32(26).bytes(message.data);
    }
    if (message.executable !== undefined) {
      writer.uint32(32).bool(message.executable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAccountInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAccountInfoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lamports = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.executable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAccountInfoResponse {
    return {
      owner: isSet(object.owner) ? globalThis.String(object.owner) : undefined,
      lamports: isSet(object.lamports) ? globalThis.Number(object.lamports) : undefined,
      data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : undefined,
      executable: isSet(object.executable) ? globalThis.Boolean(object.executable) : undefined,
    };
  },

  toJSON(message: GetAccountInfoResponse): unknown {
    const obj: any = {};
    if (message.owner !== undefined) {
      obj.owner = message.owner;
    }
    if (message.lamports !== undefined) {
      obj.lamports = Math.round(message.lamports);
    }
    if (message.data !== undefined) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.executable !== undefined) {
      obj.executable = message.executable;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAccountInfoResponse>, I>>(base?: I): GetAccountInfoResponse {
    return GetAccountInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAccountInfoResponse>, I>>(object: I): GetAccountInfoResponse {
    const message = createBaseGetAccountInfoResponse();
    message.owner = object.owner ?? undefined;
    message.lamports = object.lamports ?? undefined;
    message.data = object.data ?? undefined;
    message.executable = object.executable ?? undefined;
    return message;
  },
};

function createBaseGetOwnerRequest(): GetOwnerRequest {
  return { address: "" };
}

export const GetOwnerRequest: MessageFns<GetOwnerRequest> = {
  encode(message: GetOwnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOwnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOwnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOwnerRequest {
    return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
  },

  toJSON(message: GetOwnerRequest): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOwnerRequest>, I>>(base?: I): GetOwnerRequest {
    return GetOwnerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOwnerRequest>, I>>(object: I): GetOwnerRequest {
    const message = createBaseGetOwnerRequest();
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseGetOwnerResponse(): GetOwnerResponse {
  return { owner: "" };
}

export const GetOwnerResponse: MessageFns<GetOwnerResponse> = {
  encode(message: GetOwnerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.owner !== "") {
      writer.uint32(10).string(message.owner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOwnerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOwnerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOwnerResponse {
    return { owner: isSet(object.owner) ? globalThis.String(object.owner) : "" };
  },

  toJSON(message: GetOwnerResponse): unknown {
    const obj: any = {};
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOwnerResponse>, I>>(base?: I): GetOwnerResponse {
    return GetOwnerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOwnerResponse>, I>>(object: I): GetOwnerResponse {
    const message = createBaseGetOwnerResponse();
    message.owner = object.owner ?? "";
    return message;
  },
};

function createBaseGetTokenAccountOwnerRequest(): GetTokenAccountOwnerRequest {
  return { address: "" };
}

export const GetTokenAccountOwnerRequest: MessageFns<GetTokenAccountOwnerRequest> = {
  encode(message: GetTokenAccountOwnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTokenAccountOwnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTokenAccountOwnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTokenAccountOwnerRequest {
    return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
  },

  toJSON(message: GetTokenAccountOwnerRequest): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTokenAccountOwnerRequest>, I>>(base?: I): GetTokenAccountOwnerRequest {
    return GetTokenAccountOwnerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTokenAccountOwnerRequest>, I>>(object: I): GetTokenAccountOwnerRequest {
    const message = createBaseGetTokenAccountOwnerRequest();
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseGetTokenAccountOwnerResponse(): GetTokenAccountOwnerResponse {
  return { owner: "" };
}

export const GetTokenAccountOwnerResponse: MessageFns<GetTokenAccountOwnerResponse> = {
  encode(message: GetTokenAccountOwnerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.owner !== "") {
      writer.uint32(10).string(message.owner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTokenAccountOwnerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTokenAccountOwnerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTokenAccountOwnerResponse {
    return { owner: isSet(object.owner) ? globalThis.String(object.owner) : "" };
  },

  toJSON(message: GetTokenAccountOwnerResponse): unknown {
    const obj: any = {};
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTokenAccountOwnerResponse>, I>>(base?: I): GetTokenAccountOwnerResponse {
    return GetTokenAccountOwnerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTokenAccountOwnerResponse>, I>>(object: I): GetTokenAccountOwnerResponse {
    const message = createBaseGetTokenAccountOwnerResponse();
    message.owner = object.owner ?? "";
    return message;
  },
};

function createBaseGetAtaAddressRequest(): GetAtaAddressRequest {
  return { token: 0, owner: "" };
}

export const GetAtaAddressRequest: MessageFns<GetAtaAddressRequest> = {
  encode(message: GetAtaAddressRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== 0) {
      writer.uint32(8).int32(message.token);
    }
    if (message.owner !== "") {
      writer.uint32(18).string(message.owner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAtaAddressRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAtaAddressRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAtaAddressRequest {
    return {
      token: isSet(object.token) ? tokenFromJSON(object.token) : 0,
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
    };
  },

  toJSON(message: GetAtaAddressRequest): unknown {
    const obj: any = {};
    if (message.token !== 0) {
      obj.token = tokenToJSON(message.token);
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAtaAddressRequest>, I>>(base?: I): GetAtaAddressRequest {
    return GetAtaAddressRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAtaAddressRequest>, I>>(object: I): GetAtaAddressRequest {
    const message = createBaseGetAtaAddressRequest();
    message.token = object.token ?? 0;
    message.owner = object.owner ?? "";
    return message;
  },
};

function createBaseGetAtaAddressResponse(): GetAtaAddressResponse {
  return { ata: "" };
}

export const GetAtaAddressResponse: MessageFns<GetAtaAddressResponse> = {
  encode(message: GetAtaAddressResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ata !== "") {
      writer.uint32(10).string(message.ata);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAtaAddressResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAtaAddressResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ata = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetAtaAddressResponse {
    return { ata: isSet(object.ata) ? globalThis.String(object.ata) : "" };
  },

  toJSON(message: GetAtaAddressResponse): unknown {
    const obj: any = {};
    if (message.ata !== "") {
      obj.ata = message.ata;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetAtaAddressResponse>, I>>(base?: I): GetAtaAddressResponse {
    return GetAtaAddressResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetAtaAddressResponse>, I>>(object: I): GetAtaAddressResponse {
    const message = createBaseGetAtaAddressResponse();
    message.ata = object.ata ?? "";
    return message;
  },
};

function createBaseGetOrCreateAtaRequest(): GetOrCreateAtaRequest {
  return { token: 0, owner: "", maxAttempts: undefined };
}

export const GetOrCreateAtaRequest: MessageFns<GetOrCreateAtaRequest> = {
  encode(message: GetOrCreateAtaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== 0) {
      writer.uint32(8).int32(message.token);
    }
    if (message.owner !== "") {
      writer.uint32(18).string(message.owner);
    }
    if (message.maxAttempts !== undefined) {
      writer.uint32(24).uint32(message.maxAttempts);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOrCreateAtaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOrCreateAtaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxAttempts = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOrCreateAtaRequest {
    return {
      token: isSet(object.token) ? tokenFromJSON(object.token) : 0,
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      maxAttempts: isSet(object.maxAttempts)
        ? globalThis.Number(object.maxAttempts)
        : isSet(object.max_attempts)
        ? globalThis.Number(object.max_attempts)
        : undefined,
    };
  },

  toJSON(message: GetOrCreateAtaRequest): unknown {
    const obj: any = {};
    if (message.token !== 0) {
      obj.token = tokenToJSON(message.token);
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.maxAttempts !== undefined) {
      obj.maxAttempts = Math.round(message.maxAttempts);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOrCreateAtaRequest>, I>>(base?: I): GetOrCreateAtaRequest {
    return GetOrCreateAtaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrCreateAtaRequest>, I>>(object: I): GetOrCreateAtaRequest {
    const message = createBaseGetOrCreateAtaRequest();
    message.token = object.token ?? 0;
    message.owner = object.owner ?? "";
    message.maxAttempts = object.maxAttempts ?? undefined;
    return message;
  },
};

function createBaseGetOrCreateAtaResponse(): GetOrCreateAtaResponse {
  return { ata: "", tokenAccount: undefined, txId: undefined };
}

export const GetOrCreateAtaResponse: MessageFns<GetOrCreateAtaResponse> = {
  encode(message: GetOrCreateAtaResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ata !== "") {
      writer.uint32(10).string(message.ata);
    }
    if (message.tokenAccount !== undefined) {
      GetAccountInfoResponse.encode(message.tokenAccount, writer.uint32(18).fork()).join();
    }
    if (message.txId !== undefined) {
      writer.uint32(26).string(message.txId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOrCreateAtaResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOrCreateAtaResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ata = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokenAccount = GetAccountInfoResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.txId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOrCreateAtaResponse {
    return {
      ata: isSet(object.ata) ? globalThis.String(object.ata) : "",
      tokenAccount: isSet(object.tokenAccount)
        ? GetAccountInfoResponse.fromJSON(object.tokenAccount)
        : isSet(object.token_account)
        ? GetAccountInfoResponse.fromJSON(object.token_account)
        : undefined,
      txId: isSet(object.txId)
        ? globalThis.String(object.txId)
        : isSet(object.tx_id)
        ? globalThis.String(object.tx_id)
        : undefined,
    };
  },

  toJSON(message: GetOrCreateAtaResponse): unknown {
    const obj: any = {};
    if (message.ata !== "") {
      obj.ata = message.ata;
    }
    if (message.tokenAccount !== undefined) {
      obj.tokenAccount = GetAccountInfoResponse.toJSON(message.tokenAccount);
    }
    if (message.txId !== undefined) {
      obj.txId = message.txId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOrCreateAtaResponse>, I>>(base?: I): GetOrCreateAtaResponse {
    return GetOrCreateAtaResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOrCreateAtaResponse>, I>>(object: I): GetOrCreateAtaResponse {
    const message = createBaseGetOrCreateAtaResponse();
    message.ata = object.ata ?? "";
    message.tokenAccount = (object.tokenAccount !== undefined && object.tokenAccount !== null)
      ? GetAccountInfoResponse.fromPartial(object.tokenAccount)
      : undefined;
    message.txId = object.txId ?? undefined;
    return message;
  },
};

function createBaseExecuteTxRequest(): ExecuteTxRequest {
  return { requestId: "", ixs: [], signers: [] };
}

export const ExecuteTxRequest: MessageFns<ExecuteTxRequest> = {
  encode(message: ExecuteTxRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    for (const v of message.ixs) {
      TxIx.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.signers) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteTxRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteTxRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ixs.push(TxIx.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.signers.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteTxRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      ixs: globalThis.Array.isArray(object?.ixs) ? object.ixs.map((e: any) => TxIx.fromJSON(e)) : [],
      signers: globalThis.Array.isArray(object?.signers) ? object.signers.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: ExecuteTxRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.ixs?.length) {
      obj.ixs = message.ixs.map((e) => TxIx.toJSON(e));
    }
    if (message.signers?.length) {
      obj.signers = message.signers;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteTxRequest>, I>>(base?: I): ExecuteTxRequest {
    return ExecuteTxRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteTxRequest>, I>>(object: I): ExecuteTxRequest {
    const message = createBaseExecuteTxRequest();
    message.requestId = object.requestId ?? "";
    message.ixs = object.ixs?.map((e) => TxIx.fromPartial(e)) || [];
    message.signers = object.signers?.map((e) => e) || [];
    return message;
  },
};

function createBaseExecuteTxResponse(): ExecuteTxResponse {
  return { requestId: "", txId: "" };
}

export const ExecuteTxResponse: MessageFns<ExecuteTxResponse> = {
  encode(message: ExecuteTxResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.txId !== "") {
      writer.uint32(18).string(message.txId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteTxResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteTxResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.txId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteTxResponse {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      txId: isSet(object.txId)
        ? globalThis.String(object.txId)
        : isSet(object.tx_id)
        ? globalThis.String(object.tx_id)
        : "",
    };
  },

  toJSON(message: ExecuteTxResponse): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.txId !== "") {
      obj.txId = message.txId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteTxResponse>, I>>(base?: I): ExecuteTxResponse {
    return ExecuteTxResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteTxResponse>, I>>(object: I): ExecuteTxResponse {
    const message = createBaseExecuteTxResponse();
    message.requestId = object.requestId ?? "";
    message.txId = object.txId ?? "";
    return message;
  },
};

function createBaseGetTxStatusRequest(): GetTxStatusRequest {
  return { txId: "", confirmation: undefined };
}

export const GetTxStatusRequest: MessageFns<GetTxStatusRequest> = {
  encode(message: GetTxStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txId !== "") {
      writer.uint32(10).string(message.txId);
    }
    if (message.confirmation !== undefined) {
      writer.uint32(18).string(message.confirmation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTxStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTxStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.confirmation = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTxStatusRequest {
    return {
      txId: isSet(object.txId)
        ? globalThis.String(object.txId)
        : isSet(object.tx_id)
        ? globalThis.String(object.tx_id)
        : "",
      confirmation: isSet(object.confirmation) ? globalThis.String(object.confirmation) : undefined,
    };
  },

  toJSON(message: GetTxStatusRequest): unknown {
    const obj: any = {};
    if (message.txId !== "") {
      obj.txId = message.txId;
    }
    if (message.confirmation !== undefined) {
      obj.confirmation = message.confirmation;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTxStatusRequest>, I>>(base?: I): GetTxStatusRequest {
    return GetTxStatusRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTxStatusRequest>, I>>(object: I): GetTxStatusRequest {
    const message = createBaseGetTxStatusRequest();
    message.txId = object.txId ?? "";
    message.confirmation = object.confirmation ?? undefined;
    return message;
  },
};

function createBaseTxStatus(): TxStatus {
  return { status: "", slot: 0 };
}

export const TxStatus: MessageFns<TxStatus> = {
  encode(message: TxStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.slot !== 0) {
      writer.uint32(16).uint64(message.slot);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.slot = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxStatus {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      slot: isSet(object.slot) ? globalThis.Number(object.slot) : 0,
    };
  },

  toJSON(message: TxStatus): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.slot !== 0) {
      obj.slot = Math.round(message.slot);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxStatus>, I>>(base?: I): TxStatus {
    return TxStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxStatus>, I>>(object: I): TxStatus {
    const message = createBaseTxStatus();
    message.status = object.status ?? "";
    message.slot = object.slot ?? 0;
    return message;
  },
};

function createBaseGetTxDetailsRequest(): GetTxDetailsRequest {
  return { txId: "", commitment: undefined };
}

export const GetTxDetailsRequest: MessageFns<GetTxDetailsRequest> = {
  encode(message: GetTxDetailsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txId !== "") {
      writer.uint32(10).string(message.txId);
    }
    if (message.commitment !== undefined) {
      writer.uint32(18).string(message.commitment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTxDetailsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTxDetailsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.commitment = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTxDetailsRequest {
    return {
      txId: isSet(object.txId)
        ? globalThis.String(object.txId)
        : isSet(object.tx_id)
        ? globalThis.String(object.tx_id)
        : "",
      commitment: isSet(object.commitment) ? globalThis.String(object.commitment) : undefined,
    };
  },

  toJSON(message: GetTxDetailsRequest): unknown {
    const obj: any = {};
    if (message.txId !== "") {
      obj.txId = message.txId;
    }
    if (message.commitment !== undefined) {
      obj.commitment = message.commitment;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTxDetailsRequest>, I>>(base?: I): GetTxDetailsRequest {
    return GetTxDetailsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTxDetailsRequest>, I>>(object: I): GetTxDetailsRequest {
    const message = createBaseGetTxDetailsRequest();
    message.txId = object.txId ?? "";
    message.commitment = object.commitment ?? undefined;
    return message;
  },
};

function createBaseTxDetails(): TxDetails {
  return { stringified: "" };
}

export const TxDetails: MessageFns<TxDetails> = {
  encode(message: TxDetails, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stringified !== "") {
      writer.uint32(10).string(message.stringified);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxDetails {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stringified = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxDetails {
    return { stringified: isSet(object.stringified) ? globalThis.String(object.stringified) : "" };
  },

  toJSON(message: TxDetails): unknown {
    const obj: any = {};
    if (message.stringified !== "") {
      obj.stringified = message.stringified;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxDetails>, I>>(base?: I): TxDetails {
    return TxDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxDetails>, I>>(object: I): TxDetails {
    const message = createBaseTxDetails();
    message.stringified = object.stringified ?? "";
    return message;
  },
};

function createBaseGetTxCostRequest(): GetTxCostRequest {
  return { txId: "", denom: undefined };
}

export const GetTxCostRequest: MessageFns<GetTxCostRequest> = {
  encode(message: GetTxCostRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txId !== "") {
      writer.uint32(10).string(message.txId);
    }
    if (message.denom !== undefined) {
      writer.uint32(16).int32(message.denom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTxCostRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTxCostRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.denom = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTxCostRequest {
    return {
      txId: isSet(object.txId)
        ? globalThis.String(object.txId)
        : isSet(object.tx_id)
        ? globalThis.String(object.tx_id)
        : "",
      denom: isSet(object.denom) ? denomFromJSON(object.denom) : undefined,
    };
  },

  toJSON(message: GetTxCostRequest): unknown {
    const obj: any = {};
    if (message.txId !== "") {
      obj.txId = message.txId;
    }
    if (message.denom !== undefined) {
      obj.denom = denomToJSON(message.denom);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTxCostRequest>, I>>(base?: I): GetTxCostRequest {
    return GetTxCostRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTxCostRequest>, I>>(object: I): GetTxCostRequest {
    const message = createBaseGetTxCostRequest();
    message.txId = object.txId ?? "";
    message.denom = object.denom ?? undefined;
    return message;
  },
};

function createBaseTxCost(): TxCost {
  return { txCost: 0, denom: "" };
}

export const TxCost: MessageFns<TxCost> = {
  encode(message: TxCost, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txCost !== 0) {
      writer.uint32(9).double(message.txCost);
    }
    if (message.denom !== "") {
      writer.uint32(18).string(message.denom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxCost {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxCost();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.txCost = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.denom = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxCost {
    return {
      txCost: isSet(object.txCost)
        ? globalThis.Number(object.txCost)
        : isSet(object.tx_cost)
        ? globalThis.Number(object.tx_cost)
        : 0,
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
    };
  },

  toJSON(message: TxCost): unknown {
    const obj: any = {};
    if (message.txCost !== 0) {
      obj.txCost = message.txCost;
    }
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxCost>, I>>(base?: I): TxCost {
    return TxCost.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxCost>, I>>(object: I): TxCost {
    const message = createBaseTxCost();
    message.txCost = object.txCost ?? 0;
    message.denom = object.denom ?? "";
    return message;
  },
};

export type BaseDefinition = typeof BaseDefinition;
export const BaseDefinition = {
  name: "Base",
  fullName: "base.Base",
  methods: {
    generateHashedArray: {
      name: "GenerateHashedArray",
      requestType: GenerateHashedArrayRequest as typeof GenerateHashedArrayRequest,
      requestStream: false,
      responseType: GenerateHashedArrayResponse as typeof GenerateHashedArrayResponse,
      responseStream: false,
      options: {},
    },
    buildEd25519Ix: {
      name: "BuildEd25519Ix",
      requestType: BuildEd25519IxRequest as typeof BuildEd25519IxRequest,
      requestStream: false,
      responseType: Ed25519Pair as typeof Ed25519Pair,
      responseStream: false,
      options: {},
    },
    getAccountInfo: {
      name: "GetAccountInfo",
      requestType: GetAccountInfoRequest as typeof GetAccountInfoRequest,
      requestStream: false,
      responseType: GetAccountInfoResponse as typeof GetAccountInfoResponse,
      responseStream: false,
      options: {},
    },
    getOwner: {
      name: "GetOwner",
      requestType: GetOwnerRequest as typeof GetOwnerRequest,
      requestStream: false,
      responseType: GetOwnerResponse as typeof GetOwnerResponse,
      responseStream: false,
      options: {},
    },
    getTokenAccountOwner: {
      name: "GetTokenAccountOwner",
      requestType: GetTokenAccountOwnerRequest as typeof GetTokenAccountOwnerRequest,
      requestStream: false,
      responseType: GetTokenAccountOwnerResponse as typeof GetTokenAccountOwnerResponse,
      responseStream: false,
      options: {},
    },
    getAtaAddress: {
      name: "GetAtaAddress",
      requestType: GetAtaAddressRequest as typeof GetAtaAddressRequest,
      requestStream: false,
      responseType: GetAtaAddressResponse as typeof GetAtaAddressResponse,
      responseStream: false,
      options: {},
    },
    getOrCreateAta: {
      name: "GetOrCreateAta",
      requestType: GetOrCreateAtaRequest as typeof GetOrCreateAtaRequest,
      requestStream: false,
      responseType: GetOrCreateAtaResponse as typeof GetOrCreateAtaResponse,
      responseStream: false,
      options: {},
    },
    executeTx: {
      name: "ExecuteTx",
      requestType: ExecuteTxRequest as typeof ExecuteTxRequest,
      requestStream: false,
      responseType: ExecuteTxResponse as typeof ExecuteTxResponse,
      responseStream: false,
      options: {},
    },
    getTxStatus: {
      name: "GetTxStatus",
      requestType: GetTxStatusRequest as typeof GetTxStatusRequest,
      requestStream: false,
      responseType: TxStatus as typeof TxStatus,
      responseStream: false,
      options: {},
    },
    getTxDetails: {
      name: "GetTxDetails",
      requestType: GetTxDetailsRequest as typeof GetTxDetailsRequest,
      requestStream: false,
      responseType: TxDetails as typeof TxDetails,
      responseStream: false,
      options: {},
    },
    getTxCost: {
      name: "GetTxCost",
      requestType: GetTxCostRequest as typeof GetTxCostRequest,
      requestStream: false,
      responseType: TxCost as typeof TxCost,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface BaseServiceImplementation<CallContextExt = {}> {
  generateHashedArray(
    request: GenerateHashedArrayRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GenerateHashedArrayResponse>>;
  buildEd25519Ix(
    request: BuildEd25519IxRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<Ed25519Pair>>;
  getAccountInfo(
    request: GetAccountInfoRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetAccountInfoResponse>>;
  getOwner(request: GetOwnerRequest, context: CallContext & CallContextExt): Promise<DeepPartial<GetOwnerResponse>>;
  getTokenAccountOwner(
    request: GetTokenAccountOwnerRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetTokenAccountOwnerResponse>>;
  getAtaAddress(
    request: GetAtaAddressRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetAtaAddressResponse>>;
  getOrCreateAta(
    request: GetOrCreateAtaRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetOrCreateAtaResponse>>;
  executeTx(request: ExecuteTxRequest, context: CallContext & CallContextExt): Promise<DeepPartial<ExecuteTxResponse>>;
  getTxStatus(request: GetTxStatusRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxStatus>>;
  getTxDetails(request: GetTxDetailsRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxDetails>>;
  getTxCost(request: GetTxCostRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxCost>>;
}

export interface BaseClient<CallOptionsExt = {}> {
  generateHashedArray(
    request: DeepPartial<GenerateHashedArrayRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GenerateHashedArrayResponse>;
  buildEd25519Ix(
    request: DeepPartial<BuildEd25519IxRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<Ed25519Pair>;
  getAccountInfo(
    request: DeepPartial<GetAccountInfoRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetAccountInfoResponse>;
  getOwner(request: DeepPartial<GetOwnerRequest>, options?: CallOptions & CallOptionsExt): Promise<GetOwnerResponse>;
  getTokenAccountOwner(
    request: DeepPartial<GetTokenAccountOwnerRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetTokenAccountOwnerResponse>;
  getAtaAddress(
    request: DeepPartial<GetAtaAddressRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetAtaAddressResponse>;
  getOrCreateAta(
    request: DeepPartial<GetOrCreateAtaRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetOrCreateAtaResponse>;
  executeTx(request: DeepPartial<ExecuteTxRequest>, options?: CallOptions & CallOptionsExt): Promise<ExecuteTxResponse>;
  getTxStatus(request: DeepPartial<GetTxStatusRequest>, options?: CallOptions & CallOptionsExt): Promise<TxStatus>;
  getTxDetails(request: DeepPartial<GetTxDetailsRequest>, options?: CallOptions & CallOptionsExt): Promise<TxDetails>;
  getTxCost(request: DeepPartial<GetTxCostRequest>, options?: CallOptions & CallOptionsExt): Promise<TxCost>;
}

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
