// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: core.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Ed25519Pair, Token, tokenFromJSON, tokenToJSON } from "./base";

export const protobufPackage = "core";

export interface DomainSeparatorRequest {
}

export interface DomainSeparatorResponse {
  domainSeparator: number;
}

export interface GetPdvRequest {
  partnerId?: string | undefined;
}

export interface PdvResponse {
  pdv: string;
}

export interface MetaArg {
  key: string;
  value: string;
}

export interface CreateOrderRequest {
  requestId: string;
  partnerId: string;
  beneficiary: string;
  token: Token;
  amount: string;
  pull?: boolean | undefined;
  meta: MetaArg[];
}

export interface ReplenishRequest {
  requestId: string;
  orderTracker: string;
  token: Token;
  amount: string;
  doNotClose?: boolean | undefined;
  kaminoAmount?: string | undefined;
  meta: MetaArg[];
}

export interface TransferRequest {
  requestId: string;
  from: string;
  to: string;
  amount: string;
  token: Token;
  toToken?: Token | undefined;
  ed25519Pair?: Ed25519Pair | undefined;
  meta: MetaArg[];
}

export interface AttestOrderRequest {
  orderId: string;
  token: Token;
  amount: string;
  meta: MetaArg[];
}

export interface TxResponse {
  requestId: string;
  orderTracker: string;
  txId: string;
  position: number;
  meta: { [key: string]: string };
}

export interface TxResponse_MetaEntry {
  key: string;
  value: string;
}

function createBaseDomainSeparatorRequest(): DomainSeparatorRequest {
  return {};
}

export const DomainSeparatorRequest: MessageFns<DomainSeparatorRequest> = {
  encode(_: DomainSeparatorRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DomainSeparatorRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDomainSeparatorRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DomainSeparatorRequest {
    return {};
  },

  toJSON(_: DomainSeparatorRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DomainSeparatorRequest>, I>>(base?: I): DomainSeparatorRequest {
    return DomainSeparatorRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DomainSeparatorRequest>, I>>(_: I): DomainSeparatorRequest {
    const message = createBaseDomainSeparatorRequest();
    return message;
  },
};

function createBaseDomainSeparatorResponse(): DomainSeparatorResponse {
  return { domainSeparator: 0 };
}

export const DomainSeparatorResponse: MessageFns<DomainSeparatorResponse> = {
  encode(message: DomainSeparatorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.domainSeparator !== 0) {
      writer.uint32(8).int64(message.domainSeparator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DomainSeparatorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDomainSeparatorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.domainSeparator = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DomainSeparatorResponse {
    return {
      domainSeparator: isSet(object.domainSeparator)
        ? globalThis.Number(object.domainSeparator)
        : isSet(object.domain_separator)
        ? globalThis.Number(object.domain_separator)
        : 0,
    };
  },

  toJSON(message: DomainSeparatorResponse): unknown {
    const obj: any = {};
    if (message.domainSeparator !== 0) {
      obj.domainSeparator = Math.round(message.domainSeparator);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DomainSeparatorResponse>, I>>(base?: I): DomainSeparatorResponse {
    return DomainSeparatorResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DomainSeparatorResponse>, I>>(object: I): DomainSeparatorResponse {
    const message = createBaseDomainSeparatorResponse();
    message.domainSeparator = object.domainSeparator ?? 0;
    return message;
  },
};

function createBaseGetPdvRequest(): GetPdvRequest {
  return { partnerId: undefined };
}

export const GetPdvRequest: MessageFns<GetPdvRequest> = {
  encode(message: GetPdvRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.partnerId !== undefined) {
      writer.uint32(10).string(message.partnerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPdvRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPdvRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.partnerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPdvRequest {
    return {
      partnerId: isSet(object.partnerId)
        ? globalThis.String(object.partnerId)
        : isSet(object.partner_id)
        ? globalThis.String(object.partner_id)
        : undefined,
    };
  },

  toJSON(message: GetPdvRequest): unknown {
    const obj: any = {};
    if (message.partnerId !== undefined) {
      obj.partnerId = message.partnerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPdvRequest>, I>>(base?: I): GetPdvRequest {
    return GetPdvRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPdvRequest>, I>>(object: I): GetPdvRequest {
    const message = createBaseGetPdvRequest();
    message.partnerId = object.partnerId ?? undefined;
    return message;
  },
};

function createBasePdvResponse(): PdvResponse {
  return { pdv: "" };
}

export const PdvResponse: MessageFns<PdvResponse> = {
  encode(message: PdvResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pdv !== "") {
      writer.uint32(10).string(message.pdv);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PdvResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePdvResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pdv = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PdvResponse {
    return { pdv: isSet(object.pdv) ? globalThis.String(object.pdv) : "" };
  },

  toJSON(message: PdvResponse): unknown {
    const obj: any = {};
    if (message.pdv !== "") {
      obj.pdv = message.pdv;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PdvResponse>, I>>(base?: I): PdvResponse {
    return PdvResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PdvResponse>, I>>(object: I): PdvResponse {
    const message = createBasePdvResponse();
    message.pdv = object.pdv ?? "";
    return message;
  },
};

function createBaseMetaArg(): MetaArg {
  return { key: "", value: "" };
}

export const MetaArg: MessageFns<MetaArg> = {
  encode(message: MetaArg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MetaArg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetaArg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetaArg {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: MetaArg): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MetaArg>, I>>(base?: I): MetaArg {
    return MetaArg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetaArg>, I>>(object: I): MetaArg {
    const message = createBaseMetaArg();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseCreateOrderRequest(): CreateOrderRequest {
  return { requestId: "", partnerId: "", beneficiary: "", token: 0, amount: "", pull: undefined, meta: [] };
}

export const CreateOrderRequest: MessageFns<CreateOrderRequest> = {
  encode(message: CreateOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.partnerId !== "") {
      writer.uint32(18).string(message.partnerId);
    }
    if (message.beneficiary !== "") {
      writer.uint32(26).string(message.beneficiary);
    }
    if (message.token !== 0) {
      writer.uint32(32).int32(message.token);
    }
    if (message.amount !== "") {
      writer.uint32(42).string(message.amount);
    }
    if (message.pull !== undefined) {
      writer.uint32(48).bool(message.pull);
    }
    for (const v of message.meta) {
      MetaArg.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.partnerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.beneficiary = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.pull = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.meta.push(MetaArg.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      partnerId: isSet(object.partnerId)
        ? globalThis.String(object.partnerId)
        : isSet(object.partner_id)
        ? globalThis.String(object.partner_id)
        : "",
      beneficiary: isSet(object.beneficiary) ? globalThis.String(object.beneficiary) : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : 0,
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      pull: isSet(object.pull) ? globalThis.Boolean(object.pull) : undefined,
      meta: globalThis.Array.isArray(object?.meta) ? object.meta.map((e: any) => MetaArg.fromJSON(e)) : [],
    };
  },

  toJSON(message: CreateOrderRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.partnerId !== "") {
      obj.partnerId = message.partnerId;
    }
    if (message.beneficiary !== "") {
      obj.beneficiary = message.beneficiary;
    }
    if (message.token !== 0) {
      obj.token = tokenToJSON(message.token);
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.pull !== undefined) {
      obj.pull = message.pull;
    }
    if (message.meta?.length) {
      obj.meta = message.meta.map((e) => MetaArg.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderRequest>, I>>(base?: I): CreateOrderRequest {
    return CreateOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderRequest>, I>>(object: I): CreateOrderRequest {
    const message = createBaseCreateOrderRequest();
    message.requestId = object.requestId ?? "";
    message.partnerId = object.partnerId ?? "";
    message.beneficiary = object.beneficiary ?? "";
    message.token = object.token ?? 0;
    message.amount = object.amount ?? "";
    message.pull = object.pull ?? undefined;
    message.meta = object.meta?.map((e) => MetaArg.fromPartial(e)) || [];
    return message;
  },
};

function createBaseReplenishRequest(): ReplenishRequest {
  return {
    requestId: "",
    orderTracker: "",
    token: 0,
    amount: "",
    doNotClose: undefined,
    kaminoAmount: undefined,
    meta: [],
  };
}

export const ReplenishRequest: MessageFns<ReplenishRequest> = {
  encode(message: ReplenishRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.orderTracker !== "") {
      writer.uint32(18).string(message.orderTracker);
    }
    if (message.token !== 0) {
      writer.uint32(24).int32(message.token);
    }
    if (message.amount !== "") {
      writer.uint32(34).string(message.amount);
    }
    if (message.doNotClose !== undefined) {
      writer.uint32(40).bool(message.doNotClose);
    }
    if (message.kaminoAmount !== undefined) {
      writer.uint32(50).string(message.kaminoAmount);
    }
    for (const v of message.meta) {
      MetaArg.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReplenishRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReplenishRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orderTracker = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.doNotClose = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.kaminoAmount = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.meta.push(MetaArg.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReplenishRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      orderTracker: isSet(object.orderTracker)
        ? globalThis.String(object.orderTracker)
        : isSet(object.order_tracker)
        ? globalThis.String(object.order_tracker)
        : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : 0,
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      doNotClose: isSet(object.doNotClose)
        ? globalThis.Boolean(object.doNotClose)
        : isSet(object.do_not_close)
        ? globalThis.Boolean(object.do_not_close)
        : undefined,
      kaminoAmount: isSet(object.kaminoAmount)
        ? globalThis.String(object.kaminoAmount)
        : isSet(object.kamino_amount)
        ? globalThis.String(object.kamino_amount)
        : undefined,
      meta: globalThis.Array.isArray(object?.meta)
        ? object.meta.map((e: any) => MetaArg.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ReplenishRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.orderTracker !== "") {
      obj.orderTracker = message.orderTracker;
    }
    if (message.token !== 0) {
      obj.token = tokenToJSON(message.token);
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.doNotClose !== undefined) {
      obj.doNotClose = message.doNotClose;
    }
    if (message.kaminoAmount !== undefined) {
      obj.kaminoAmount = message.kaminoAmount;
    }
    if (message.meta?.length) {
      obj.meta = message.meta.map((e) => MetaArg.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReplenishRequest>, I>>(base?: I): ReplenishRequest {
    return ReplenishRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReplenishRequest>, I>>(object: I): ReplenishRequest {
    const message = createBaseReplenishRequest();
    message.requestId = object.requestId ?? "";
    message.orderTracker = object.orderTracker ?? "";
    message.token = object.token ?? 0;
    message.amount = object.amount ?? "";
    message.doNotClose = object.doNotClose ?? undefined;
    message.kaminoAmount = object.kaminoAmount ?? undefined;
    message.meta = object.meta?.map((e) => MetaArg.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTransferRequest(): TransferRequest {
  return {
    requestId: "",
    from: "",
    to: "",
    amount: "",
    token: 0,
    toToken: undefined,
    ed25519Pair: undefined,
    meta: [],
  };
}

export const TransferRequest: MessageFns<TransferRequest> = {
  encode(message: TransferRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.from !== "") {
      writer.uint32(18).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(26).string(message.to);
    }
    if (message.amount !== "") {
      writer.uint32(34).string(message.amount);
    }
    if (message.token !== 0) {
      writer.uint32(40).int32(message.token);
    }
    if (message.toToken !== undefined) {
      writer.uint32(48).int32(message.toToken);
    }
    if (message.ed25519Pair !== undefined) {
      Ed25519Pair.encode(message.ed25519Pair, writer.uint32(58).fork()).join();
    }
    for (const v of message.meta) {
      MetaArg.encode(v!, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TransferRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransferRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.toToken = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.ed25519Pair = Ed25519Pair.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.meta.push(MetaArg.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TransferRequest {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : 0,
      toToken: isSet(object.toToken)
        ? tokenFromJSON(object.toToken)
        : isSet(object.to_token)
        ? tokenFromJSON(object.to_token)
        : undefined,
      ed25519Pair: isSet(object.ed25519Pair)
        ? Ed25519Pair.fromJSON(object.ed25519Pair)
        : isSet(object.ed25519_pair)
        ? Ed25519Pair.fromJSON(object.ed25519_pair)
        : undefined,
      meta: globalThis.Array.isArray(object?.meta)
        ? object.meta.map((e: any) => MetaArg.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TransferRequest): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.token !== 0) {
      obj.token = tokenToJSON(message.token);
    }
    if (message.toToken !== undefined) {
      obj.toToken = tokenToJSON(message.toToken);
    }
    if (message.ed25519Pair !== undefined) {
      obj.ed25519Pair = Ed25519Pair.toJSON(message.ed25519Pair);
    }
    if (message.meta?.length) {
      obj.meta = message.meta.map((e) => MetaArg.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TransferRequest>, I>>(base?: I): TransferRequest {
    return TransferRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TransferRequest>, I>>(object: I): TransferRequest {
    const message = createBaseTransferRequest();
    message.requestId = object.requestId ?? "";
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.amount = object.amount ?? "";
    message.token = object.token ?? 0;
    message.toToken = object.toToken ?? undefined;
    message.ed25519Pair = (object.ed25519Pair !== undefined && object.ed25519Pair !== null)
      ? Ed25519Pair.fromPartial(object.ed25519Pair)
      : undefined;
    message.meta = object.meta?.map((e) => MetaArg.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAttestOrderRequest(): AttestOrderRequest {
  return { orderId: "", token: 0, amount: "", meta: [] };
}

export const AttestOrderRequest: MessageFns<AttestOrderRequest> = {
  encode(message: AttestOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.token !== 0) {
      writer.uint32(16).int32(message.token);
    }
    if (message.amount !== "") {
      writer.uint32(26).string(message.amount);
    }
    for (const v of message.meta) {
      MetaArg.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AttestOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttestOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.token = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.meta.push(MetaArg.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AttestOrderRequest {
    return {
      orderId: isSet(object.orderId)
        ? globalThis.String(object.orderId)
        : isSet(object.order_id)
        ? globalThis.String(object.order_id)
        : "",
      token: isSet(object.token) ? tokenFromJSON(object.token) : 0,
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      meta: globalThis.Array.isArray(object?.meta) ? object.meta.map((e: any) => MetaArg.fromJSON(e)) : [],
    };
  },

  toJSON(message: AttestOrderRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.token !== 0) {
      obj.token = tokenToJSON(message.token);
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.meta?.length) {
      obj.meta = message.meta.map((e) => MetaArg.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AttestOrderRequest>, I>>(base?: I): AttestOrderRequest {
    return AttestOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AttestOrderRequest>, I>>(object: I): AttestOrderRequest {
    const message = createBaseAttestOrderRequest();
    message.orderId = object.orderId ?? "";
    message.token = object.token ?? 0;
    message.amount = object.amount ?? "";
    message.meta = object.meta?.map((e) => MetaArg.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTxResponse(): TxResponse {
  return { requestId: "", orderTracker: "", txId: "", position: 0, meta: {} };
}

export const TxResponse: MessageFns<TxResponse> = {
  encode(message: TxResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestId !== "") {
      writer.uint32(10).string(message.requestId);
    }
    if (message.orderTracker !== "") {
      writer.uint32(18).string(message.orderTracker);
    }
    if (message.txId !== "") {
      writer.uint32(26).string(message.txId);
    }
    if (message.position !== 0) {
      writer.uint32(32).int64(message.position);
    }
    globalThis.Object.entries(message.meta).forEach(([key, value]: [string, string]) => {
      TxResponse_MetaEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orderTracker = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.txId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.position = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = TxResponse_MetaEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.meta[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxResponse {
    return {
      requestId: isSet(object.requestId)
        ? globalThis.String(object.requestId)
        : isSet(object.request_id)
        ? globalThis.String(object.request_id)
        : "",
      orderTracker: isSet(object.orderTracker)
        ? globalThis.String(object.orderTracker)
        : isSet(object.order_tracker)
        ? globalThis.String(object.order_tracker)
        : "",
      txId: isSet(object.txId)
        ? globalThis.String(object.txId)
        : isSet(object.tx_id)
        ? globalThis.String(object.tx_id)
        : "",
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
      meta: isObject(object.meta)
        ? (globalThis.Object.entries(object.meta) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: TxResponse): unknown {
    const obj: any = {};
    if (message.requestId !== "") {
      obj.requestId = message.requestId;
    }
    if (message.orderTracker !== "") {
      obj.orderTracker = message.orderTracker;
    }
    if (message.txId !== "") {
      obj.txId = message.txId;
    }
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    if (message.meta) {
      const entries = globalThis.Object.entries(message.meta) as [string, string][];
      if (entries.length > 0) {
        obj.meta = {};
        entries.forEach(([k, v]) => {
          obj.meta[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxResponse>, I>>(base?: I): TxResponse {
    return TxResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxResponse>, I>>(object: I): TxResponse {
    const message = createBaseTxResponse();
    message.requestId = object.requestId ?? "";
    message.orderTracker = object.orderTracker ?? "";
    message.txId = object.txId ?? "";
    message.position = object.position ?? 0;
    message.meta = (globalThis.Object.entries(object.meta ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseTxResponse_MetaEntry(): TxResponse_MetaEntry {
  return { key: "", value: "" };
}

export const TxResponse_MetaEntry: MessageFns<TxResponse_MetaEntry> = {
  encode(message: TxResponse_MetaEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TxResponse_MetaEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTxResponse_MetaEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TxResponse_MetaEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: TxResponse_MetaEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TxResponse_MetaEntry>, I>>(base?: I): TxResponse_MetaEntry {
    return TxResponse_MetaEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TxResponse_MetaEntry>, I>>(object: I): TxResponse_MetaEntry {
    const message = createBaseTxResponse_MetaEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

export type CoreDefinition = typeof CoreDefinition;
export const CoreDefinition = {
  name: "Core",
  fullName: "core.Core",
  methods: {
    domainSeparator: {
      name: "DomainSeparator",
      requestType: DomainSeparatorRequest as typeof DomainSeparatorRequest,
      requestStream: false,
      responseType: DomainSeparatorResponse as typeof DomainSeparatorResponse,
      responseStream: false,
      options: {},
    },
    getPdv: {
      name: "GetPdv",
      requestType: GetPdvRequest as typeof GetPdvRequest,
      requestStream: false,
      responseType: PdvResponse as typeof PdvResponse,
      responseStream: false,
      options: {},
    },
    createOrder: {
      name: "CreateOrder",
      requestType: CreateOrderRequest as typeof CreateOrderRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    replenish: {
      name: "Replenish",
      requestType: ReplenishRequest as typeof ReplenishRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    transfer: {
      name: "Transfer",
      requestType: TransferRequest as typeof TransferRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
    attestOrder: {
      name: "AttestOrder",
      requestType: AttestOrderRequest as typeof AttestOrderRequest,
      requestStream: false,
      responseType: TxResponse as typeof TxResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface CoreServiceImplementation<CallContextExt = {}> {
  domainSeparator(
    request: DomainSeparatorRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<DomainSeparatorResponse>>;
  getPdv(request: GetPdvRequest, context: CallContext & CallContextExt): Promise<DeepPartial<PdvResponse>>;
  createOrder(request: CreateOrderRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
  replenish(request: ReplenishRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
  transfer(request: TransferRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
  attestOrder(request: AttestOrderRequest, context: CallContext & CallContextExt): Promise<DeepPartial<TxResponse>>;
}

export interface CoreClient<CallOptionsExt = {}> {
  domainSeparator(
    request: DeepPartial<DomainSeparatorRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<DomainSeparatorResponse>;
  getPdv(request: DeepPartial<GetPdvRequest>, options?: CallOptions & CallOptionsExt): Promise<PdvResponse>;
  createOrder(request: DeepPartial<CreateOrderRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
  replenish(request: DeepPartial<ReplenishRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
  transfer(request: DeepPartial<TransferRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
  attestOrder(request: DeepPartial<AttestOrderRequest>, options?: CallOptions & CallOptionsExt): Promise<TxResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
